/**
 * AUTO-GENERATED by scripts/export-categories.mjs — do not hand-edit.
 *
 * Category names that exist in MORE THAN ONE L1 sector. Two such pages
 * would otherwise emit a byte-identical <title> and meta description and
 * compete with each other in search — e.g. before this list,
 *   /it-services-agencies/game-development-services
 *   /software-saas/game-development
 * both titled "Top Game Development Companies (2026) - Reviews & Pricing".
 *
 * Names are normalised (lowercased, non-alphanumerics collapsed to single
 * spaces) so slug/punctuation variations still match.
 *
 * Collisions: 51 names across 106 category rows.
 * Derived from app/config/categories-data.ts (8849 rows).
 */

export const CROSS_SECTOR_NAME_COLLISIONS: ReadonlySet<string> = new Set([
  'accounting firms',                           // Accounting Firms — it-services-agencies, professional-services
  'advertising agencies',                       // Advertising Agencies — professional-services, it-services-agencies
  'affiliate marketing agencies',               // Affiliate Marketing Agencies — professional-services, it-services-agencies
  'ai meeting assistants',                      // AI Meeting Assistants — ai-ml, software-saas
  'app store optimization aso',                 // App Store Optimization (ASO) — it-services-agencies, software-saas
  'background check services',                  // Background Check Services — professional-services, it-services-agencies
  'brand strategy consultants',                 // Brand Strategy Consultants — professional-services, it-services-agencies
  'branding agencies',                          // Branding Agencies — it-services-agencies, professional-services
  'business consulting',                        // Business Consulting — professional-services, it-services-agencies
  'content marketing',                          // Content Marketing — it-services-agencies, software-saas
  'content marketing agencies',                 // Content Marketing Agencies — it-services-agencies, professional-services
  'conversion rate optimization cro',           // Conversion Rate Optimization (CRO) — it-services-agencies, software-saas
  'corporate event planners',                   // Corporate Event Planners — local-businesses, professional-services
  'creative agencies',                          // Creative Agencies — it-services-agencies, professional-services
  'cybersecurity',                              // Cybersecurity — it-services-agencies, ai-ml
  'digital marketing agencies',                 // Digital Marketing Agencies — it-services-agencies, professional-services
  'ecommerce platforms',                        // Ecommerce Platforms — software-saas, it-services-agencies
  'event marketing agencies',                   // Event Marketing Agencies — professional-services, it-services-agencies
  'executive search firms',                     // Executive Search Firms — it-services-agencies, professional-services
  'experiential marketing agencies',            // Experiential Marketing Agencies — it-services-agencies, professional-services
  'financial planning analysis fp a',           // Financial Planning & Analysis (FP&A) — software-saas, it-services-agencies
  'game development',                           // Game Development — it-services-agencies, software-saas
  'home inspectors',                            // Home Inspectors — local-businesses, professional-services
  'influencer marketing agencies',              // Influencer Marketing Agencies — it-services-agencies, professional-services
  'insurance brokers',                          // Insurance Brokers — professional-services, local-businesses
  'interior designers',                         // Interior Designers — professional-services, local-businesses
  'knowledge management',                       // Knowledge Management — ai-ml, software-saas
  'legal services',                             // Legal Services — it-services-agencies, professional-services
  'localization services',                      // Localization Services — professional-services, it-services-agencies
  'media buying agencies',                      // Media Buying Agencies — professional-services, it-services-agencies
  'nutrition coaches',                          // Nutrition Coaches — local-businesses, professional-services
  'photography',                                // Photography — it-services-agencies, ai-ml
  'product design',                             // Product Design — it-services-agencies, ai-ml
  'product management',                         // Product Management — software-saas, ai-ml
  'programmatic advertising agencies',          // Programmatic Advertising Agencies — professional-services, it-services-agencies
  'property management companies',              // Property Management Companies — it-services-agencies, local-businesses
  'public relations',                           // Public relations — ai-ml, professional-services
  'real estate appraisers',                     // Real Estate Appraisers — local-businesses, professional-services
  'real estate photographers',                  // Real Estate Photographers — local-businesses, professional-services
  'real estate services',                       // Real Estate Services — local-businesses, it-services-agencies
  'returnship programs',                        // Returnship Programs — professional-services, startups-innovation
  'revenue based financing lenders',            // Revenue-Based Financing Lenders — professional-services, startups-innovation
  'seo agencies',                               // SEO Agencies — it-services-agencies, professional-services
  'smart contract audit firms',                 // Smart Contract Audit Firms — startups-innovation, professional-services
  'social media marketing',                     // Social Media Marketing — it-services-agencies, software-saas
  'software testing',                           // Software testing — ai-ml, software-saas
  'staffing agencies',                          // Staffing Agencies — it-services-agencies, professional-services
  'tax preparation services',                   // Tax Preparation Services — it-services-agencies, professional-services
  'title companies',                            // Title Companies — local-businesses, professional-services
  'transcription',                              // Transcription — professional-services, ai-ml
  'web hosting services',                       // Web Hosting Services — software-saas, it-services-agencies
])

/** Normalise a category name for collision lookup. */
export function normalizeCategoryName(name: string): string {
  return (name || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

/** True when this name is reused by another sector and needs qualifying. */
export function isCrossSectorCollision(name: string): boolean {
  return CROSS_SECTOR_NAME_COLLISIONS.has(normalizeCategoryName(name))
}
