-- ============================================================
-- InfoWebWorld - Repair company-listing country_id (GLOBAL, all seeds)
--
-- Bug: the `countries` table shipped with only ~10 rows (US, IN, GB, CA, AU,
-- DE, FR, NL, SG, AE). Seeds set country_id via
--   COALESCE((SELECT id FROM countries WHERE code = ?), <US fallback>)
-- so every company HQ'd outside those ~10 silently got the US id, and the
-- public /profile + category pages render the country from that FK -> they
-- showed "United States" (e.g. Montevideo, United States for a Uruguay firm).
--
-- (1) add every country the seeds use (INSERT IGNORE - existing rows untouched),
-- (2) repair country_id on ALL seeded company listings by matching the country
--     name already stored correctly at the end of hq_location.
-- Scoped to user_id IS NULL (seeded/claimable rows only) so real users' listings
-- are never modified. Safe + idempotent. Run in phpMyAdmin, then REDEPLOY.
-- Generated by scripts/gen-it-companies-500-sql.mjs - do not edit by hand.
-- ============================================================

INSERT IGNORE INTO countries (name, code, phone_code, sort_order) VALUES
  ('United States', 'US', '+1', 210),
  ('Canada', 'CA', '+1', 211),
  ('United Kingdom', 'GB', '+44', 212),
  ('Ireland', 'IE', '+353', 213),
  ('Germany', 'DE', '+49', 214),
  ('Austria', 'AT', '+43', 215),
  ('Switzerland', 'CH', '+41', 216),
  ('Netherlands', 'NL', '+31', 217),
  ('Belgium', 'BE', '+32', 218),
  ('Sweden', 'SE', '+46', 219),
  ('Denmark', 'DK', '+45', 220),
  ('Norway', 'NO', '+47', 221),
  ('Finland', 'FI', '+358', 222),
  ('Spain', 'ES', '+34', 223),
  ('Portugal', 'PT', '+351', 224),
  ('France', 'FR', '+33', 225),
  ('Italy', 'IT', '+39', 226),
  ('Greece', 'GR', '+30', 227),
  ('Australia', 'AU', '+61', 228),
  ('New Zealand', 'NZ', '+64', 229),
  ('United Arab Emirates', 'AE', '+971', 230),
  ('Saudi Arabia', 'SA', '+966', 231),
  ('Israel', 'IL', '+972', 232),
  ('Turkey', 'TR', '+90', 233),
  ('Egypt', 'EG', '+20', 234),
  ('South Africa', 'ZA', '+27', 235),
  ('Nigeria', 'NG', '+234', 236),
  ('Ghana', 'GH', '+233', 237),
  ('Kenya', 'KE', '+254', 238),
  ('India', 'IN', '+91', 239),
  ('Pakistan', 'PK', '+92', 240),
  ('Bangladesh', 'BD', '+880', 241),
  ('Sri Lanka', 'LK', '+94', 242),
  ('Nepal', 'NP', '+977', 243),
  ('Vietnam', 'VN', '+84', 244),
  ('Philippines', 'PH', '+63', 245),
  ('Indonesia', 'ID', '+62', 246),
  ('Thailand', 'TH', '+66', 247),
  ('Malaysia', 'MY', '+60', 248),
  ('Singapore', 'SG', '+65', 249),
  ('Hong Kong', 'HK', '+852', 250),
  ('Japan', 'JP', '+81', 251),
  ('Ukraine', 'UA', '+380', 252),
  ('Poland', 'PL', '+48', 253),
  ('Romania', 'RO', '+40', 254),
  ('Bulgaria', 'BG', '+359', 255),
  ('Czechia', 'CZ', '+420', 256),
  ('Serbia', 'RS', '+381', 257),
  ('Hungary', 'HU', '+36', 258),
  ('Slovakia', 'SK', '+421', 259),
  ('Slovenia', 'SI', '+386', 260),
  ('Croatia', 'HR', '+385', 261),
  ('Estonia', 'EE', '+372', 262),
  ('Latvia', 'LV', '+371', 263),
  ('Lithuania', 'LT', '+370', 264),
  ('Brazil', 'BR', '+55', 265),
  ('Mexico', 'MX', '+52', 266),
  ('Argentina', 'AR', '+54', 267),
  ('Colombia', 'CO', '+57', 268),
  ('Chile', 'CL', '+56', 269),
  ('Peru', 'PE', '+51', 270),
  ('Uruguay', 'UY', '+598', 271),
  ('Costa Rica', 'CR', '+506', 272);

UPDATE submissions s
  JOIN countries c ON c.name = TRIM(SUBSTRING_INDEX(s.hq_location, ',', -1))
   SET s.country_id = c.id
 WHERE s.listing_mode = 'company'
   AND s.user_id IS NULL
   AND s.hq_location LIKE '%,%';

-- Verify (should return 0 rows): seeded companies still on the US id whose
-- hq_location is NOT actually United States.
-- SELECT s.slug, s.hq_location, co.name AS shows
--   FROM submissions s JOIN countries co ON co.id = s.country_id
--  WHERE s.listing_mode='company' AND s.user_id IS NULL
--    AND co.code='US' AND s.hq_location NOT LIKE '%United States%';
