-- ============================================================
-- GO-LIVE - xlsx-60 seed. Flips status 'pending' -> 'active' so the listings
-- render (/company/[slug] for products, /profile/[slug] for companies).
-- Run AFTER loading the 3 seed files AND reviewing in /iww-hq/submissions.
-- Then REDEPLOY (company /profile pages are SSG, built at deploy time).
-- Scoped to these exact slugs + unclaimed rows, so it can never touch a real
-- user's listing. They stay UNCLAIMED + FREE (payment 'unpaid', user_id NULL).
-- Re-runnable. Generated by scripts/gen-xlsx-seeds.mjs.
-- ============================================================

UPDATE submissions
   SET status = 'active', activated_at = NOW()
 WHERE user_id IS NULL
   AND status = 'pending'
   AND slug IN ('quillbot', 'bardeen', 'thoughtspot', 'teachable', 'be-my-eyes', 'tidio', 'botpress', 'flutterflow', 'lindy', 'magicschool', 'bill-com', 'sisense', 'brandfolder', 'aircall', 'pendo', 'nutshell', 'paylocity', 'jumpcloud', 'sage-intacct', 'tipalti', 'concentrix', 'door3', 'mutual-mobile', 'cprime', 'closeloop', 'brainhub', 'mindk', 'trio', 'arkenea', 'dom-and-tom', 'outschool', 'watershed', 'solana-labs', 'rivian', 'khan-academy', 'lucid-motors', 'maven', 'pachama', 'aptos', 'polestar', 'hok', 'indinero', 'perkins-and-will', 'stantec', 'wsp', 'robert-walters', 'willis-towers-watson', 'perella-weinberg', 'marcum', 'cliftonlarsonallen', 'olive-garden', 'roto-rooter', 'mr-electric', 'midas', 'carmax', 'great-clips', 'gap', 'planet-fitness', 'corepower-yoga', 'the-cheesecake-factory');

-- Verify (expect 60):
-- SELECT listing_mode, COUNT(*) FROM submissions
--  WHERE status='active' AND slug IN ('quillbot', 'bardeen', 'thoughtspot', 'teachable', 'be-my-eyes', 'tidio', 'botpress', 'flutterflow', 'lindy', 'magicschool', 'bill-com', 'sisense', 'brandfolder', 'aircall', 'pendo', 'nutshell', 'paylocity', 'jumpcloud', 'sage-intacct', 'tipalti', 'concentrix', 'door3', 'mutual-mobile', 'cprime', 'closeloop', 'brainhub', 'mindk', 'trio', 'arkenea', 'dom-and-tom', 'outschool', 'watershed', 'solana-labs', 'rivian', 'khan-academy', 'lucid-motors', 'maven', 'pachama', 'aptos', 'polestar', 'hok', 'indinero', 'perkins-and-will', 'stantec', 'wsp', 'robert-walters', 'willis-towers-watson', 'perella-weinberg', 'marcum', 'cliftonlarsonallen', 'olive-garden', 'roto-rooter', 'mr-electric', 'midas', 'carmax', 'great-clips', 'gap', 'planet-fitness', 'corepower-yoga', 'the-cheesecake-factory') GROUP BY listing_mode;
