-- ============================================================
-- Screenshots for the 10 xlsx AI/ML products. Captured from each product's
-- live website (2 shots each) and uploaded to the InfoWebWorld file store.
-- Run in phpMyAdmin AFTER seed-xlsx-aiml-products.sql (works pending or active).
-- Re-runnable: each UPDATE overwrites one slug's screenshots.
-- Generated by scripts/capture-xlsx-aiml-screenshots.mjs.
-- ============================================================

UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d74574db6_1781847877.png', '/api/file/logos/6a34d74716c69_1781847879.png') WHERE slug = 'quillbot' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d74dbd1a8_1781847885.png', '/api/file/logos/6a34d74eeee03_1781847886.png') WHERE slug = 'bardeen' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d755ce770_1781847893.png', '/api/file/logos/6a34d7577468a_1781847895.png') WHERE slug = 'thoughtspot' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d75ee8862_1781847902.png', '/api/file/logos/6a34d7602ddb6_1781847904.png') WHERE slug = 'teachable' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d7671d229_1781847911.png', '/api/file/logos/6a34d7684c4ae_1781847912.png') WHERE slug = 'be-my-eyes' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d76ea972f_1781847918.png', '/api/file/logos/6a34d7707bbc5_1781847920.png') WHERE slug = 'tidio' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d777a05d3_1781847927.png', '/api/file/logos/6a34d77b2a982_1781847931.png') WHERE slug = 'botpress' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d782287d3_1781847938.png', '/api/file/logos/6a34d7837505d_1781847939.png') WHERE slug = 'flutterflow' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d78a7da7f_1781847946.png', '/api/file/logos/6a34d78c10ff2_1781847948.png') WHERE slug = 'lindy' AND listing_mode = 'product';
UPDATE submissions SET screenshots = JSON_ARRAY('/api/file/logos/6a34d79306883_1781847955.png', '/api/file/logos/6a34d79452b13_1781847956.png') WHERE slug = 'magicschool' AND listing_mode = 'product';
