-- ============================================================
-- InfoWebWorld - xlsx LOCAL BUSINESS listings (10, Yelp design)
-- Generated by scripts/gen-xlsx-seeds.mjs - do not edit by hand.
-- Source: InfoWebWorld-Companies-by-Category.xlsx (60 companies).
-- All data real / web-verified. status='pending', user_id=NULL (claimable).
-- Re-runnable: deletes its own slugs first. Run in phpMyAdmin -> SQL.
-- ============================================================

SET @free_plan        := (SELECT id FROM plans WHERE is_active = 1 ORDER BY price ASC LIMIT 1);
SET @fallback_country := (SELECT id FROM countries WHERE code = 'US' LIMIT 1);
SET @lb_sector       := (SELECT id FROM categories WHERE slug = 'local-businesses' AND level = 1 LIMIT 1);

DELETE FROM submissions WHERE listing_mode = 'company' AND user_id IS NULL AND slug IN ('olive-garden', 'roto-rooter', 'mr-electric', 'midas', 'carmax', 'great-clips', 'gap', 'planet-fitness', 'corepower-yoga', 'the-cheesecake-factory');

-- Olive Garden (food - american-restaurants)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Olive Garden', 'olive-garden', 'Olive Garden Team', 'info@olivegarden.com',
  '+1', NULL, 'https://www.olivegarden.com',
  COALESCE((SELECT id FROM categories WHERE slug='american-restaurants' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Orlando', 'FL', 'Orlando, FL, US',
  'Italian-American casual dining - unlimited breadsticks, soups, and salads since 1982.', 'Olive Garden is the largest Italian-themed full-service casual dining chain in the United States, with over 900 locations nationwide. Founded in Orlando, Florida in 1982 and part of Darden Restaurants since 1995, the chain is known for its unlimited breadsticks, soups, and salads served with every meal. The menu features a wide range of Italian-American pasta, seafood, and chicken dishes prepared fresh daily.', 'https://www.google.com/s2/favicons?domain=olivegarden.com&sz=256',
  1982, '500+', 'https://www.linkedin.com/company/olivegarden', 'https://twitter.com/olivegarden', 'https://www.facebook.com/OliveGarden/',
  'company', 0, '["Italian-American Cuisine","Casual Dining","Family Friendly","Dine-In & Takeout"]', 0, NULL,
  '$$', '[{"day":"Mon","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Tue","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Wed","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Thu","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Fri","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Sat","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Sun","time":"11:00 AM - 10:00 PM","closed":false}]', '["takeout","delivery","credit_cards","wifi","vegetarian","outdoor_seating","reservations","parking","wheelchair"]', '[{"name":"Chicken Alfredo","price":"$20.49","photo":""},{"name":"Lasagna Classico","price":"$18.49","photo":""},{"name":"Tour of Italy (Chicken Parmigiana, Lasagna, Fettuccine Alfredo)","price":"$23.99","photo":""},{"name":"Shrimp Scampi","price":"$22.49","photo":""},{"name":"Never Ending Pasta Bowl","price":"$14.99","photo":""},{"name":"Unlimited Soup, Salad & Breadsticks","price":"$13.49","photo":""},{"name":"Eggplant Parmigiana","price":"$18.49","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- Roto-Rooter (home-services - plumbers)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Roto-Rooter', 'roto-rooter', 'Roto-Rooter Team', 'info@rotorooter.com',
  '+1', NULL, 'https://www.rotorooter.com',
  COALESCE((SELECT id FROM categories WHERE slug='plumbers' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Cincinnati', 'OH', 'Cincinnati, OH, US',
  'North America''s largest plumbing and drain service - available 24/7/365 since 1935.', 'Roto-Rooter is North America''s largest provider of plumbing, drain cleaning, and water damage cleanup services, operating over 600 service locations across the US and Canada. Founded in 1935 in Des Moines, Iowa, the company pioneered the mechanical drain-cleaning machine and has since expanded into full-service plumbing repair, sewer inspection, and water damage restoration. A subsidiary of Chemed Corporation, Roto-Rooter dispatches licensed technicians 24 hours a day, 7 days a week with no extra charge for nights, weekends, or holidays.', 'https://www.google.com/s2/favicons?domain=rotorooter.com&sz=256',
  1935, '500+', 'https://www.linkedin.com/company/roto-rooter', 'https://twitter.com/rotorooter', NULL,
  'company', 0, '["Plumbing Repair","Drain Cleaning","Water Damage Cleanup","Emergency Service","24/7 Availability"]', 0, NULL,
  '$$', '[{"day":"Mon","time":"Open 24 Hours","closed":false},{"day":"Tue","time":"Open 24 Hours","closed":false},{"day":"Wed","time":"Open 24 Hours","closed":false},{"day":"Thu","time":"Open 24 Hours","closed":false},{"day":"Fri","time":"Open 24 Hours","closed":false},{"day":"Sat","time":"Open 24 Hours","closed":false},{"day":"Sun","time":"Open 24 Hours","closed":false}]', '["free_estimates","licensed_insured","emergency_service","financing","warranty","credit_cards"]', '[{"name":"Drain Cleaning (Sink or Tub)","price":"$180 - $450","photo":""},{"name":"Main Sewer Line Cleaning","price":"$350 - $600","photo":""},{"name":"Sewer Camera Inspection","price":"$295 - $350","photo":""},{"name":"Hydro Jetting","price":"$500 - $900","photo":""},{"name":"Water Heater Repair or Replacement","price":"$$","photo":""},{"name":"Water Damage Cleanup","price":"$$","photo":""},{"name":"Emergency Plumbing Service","price":"$$","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- Mr. Electric (home-services - electricians)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Mr. Electric', 'mr-electric', 'Mr. Electric Team', 'info@mrelectric.com',
  '+1', NULL, 'https://www.mrelectric.com',
  COALESCE((SELECT id FROM categories WHERE slug='electricians' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Waco', 'TX', 'Waco, TX, US',
  'Residential and commercial electrical services from licensed technicians - upfront pricing, no surprises.', 'Mr. Electric is a global franchise network of licensed electricians providing residential and commercial electrical installation and repair services at approximately 200 locations across North America. Founded in 1994 and headquartered in Waco, Texas, Mr. Electric is part of Neighborly, the world''s largest home services franchise group. The company offers upfront flat-rate pricing, 24/7 emergency dispatch, and guaranteed workmanship on every job.', 'https://www.google.com/s2/favicons?domain=mrelectric.com&sz=256',
  1994, '51-200', 'https://www.linkedin.com/company/mr--electric', 'https://twitter.com/MrElectric', NULL,
  'company', 0, '["Licensed Electricians","Residential & Commercial","Emergency Service","Upfront Pricing"]', 0, NULL,
  '$$', '[{"day":"Mon","time":"7:00 AM - 6:00 PM","closed":false},{"day":"Tue","time":"7:00 AM - 6:00 PM","closed":false},{"day":"Wed","time":"7:00 AM - 6:00 PM","closed":false},{"day":"Thu","time":"7:00 AM - 6:00 PM","closed":false},{"day":"Fri","time":"7:00 AM - 6:00 PM","closed":false},{"day":"Sat","time":"9:00 AM - 3:00 PM","closed":false},{"day":"Sun","time":"","closed":true}]', '["free_estimates","licensed_insured","emergency_service","financing","warranty","credit_cards"]', '[{"name":"Electrical Panel Upgrade","price":"$$","photo":""},{"name":"Outlet or Switch Installation","price":"$100 - $300","photo":""},{"name":"Ceiling Fan Installation","price":"$$","photo":""},{"name":"EV Charger Installation","price":"$$","photo":""},{"name":"Generator Hookup","price":"$$","photo":""},{"name":"Whole-Home Electrical Inspection","price":"$$","photo":""},{"name":"Emergency Electrical Repair","price":"$$","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- Midas (automotive - auto-repair-shops)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Midas', 'midas', 'Midas Team', 'info@midas.com',
  '+1', NULL, 'https://www.midas.com',
  COALESCE((SELECT id FROM categories WHERE slug='auto-repair-shops' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Palm Beach Gardens', 'FL', 'Palm Beach Gardens, FL, US',
  'Full-service auto repair and maintenance from one of the world''s largest automotive service chains since 1956.', 'Midas is one of the world''s largest automotive service providers, with approximately 2,100 franchised and company-owned locations across 13 countries. Founded in 1956 in Macon, Georgia, the chain originally specialized in muffler and exhaust service before expanding to brakes, oil changes, tires, steering, suspension, and fleet maintenance. Midas is now a subsidiary of Mavis Tire Express Services Corp. and offers services for conventional, hybrid, and electric vehicles.', 'https://www.google.com/s2/favicons?domain=midas.com&sz=256',
  1956, '500+', 'https://www.linkedin.com/company/midas-international', 'https://twitter.com/midas_service', NULL,
  'company', 0, '["Auto Repair","Brakes & Oil Changes","Tires & Alignment","Fleet Service"]', 0, NULL,
  '$$', '[{"day":"Mon","time":"7:30 AM - 6:00 PM","closed":false},{"day":"Tue","time":"7:30 AM - 6:00 PM","closed":false},{"day":"Wed","time":"7:30 AM - 6:00 PM","closed":false},{"day":"Thu","time":"7:30 AM - 6:00 PM","closed":false},{"day":"Fri","time":"7:30 AM - 6:00 PM","closed":false},{"day":"Sat","time":"7:30 AM - 6:00 PM","closed":false},{"day":"Sun","time":"","closed":true}]', '["free_estimates","credit_cards","financing","warranty","wheelchair"]', '[{"name":"Conventional Oil Change","price":"$27 - $30","photo":""},{"name":"Full Synthetic Oil Change","price":"$59.99 - $90","photo":""},{"name":"Brake Inspection","price":"$19.99","photo":""},{"name":"Brake Pad Replacement (per axle)","price":"$100 - $300","photo":""},{"name":"Tire Rotation","price":"$$","photo":""},{"name":"Wheel Alignment","price":"$$","photo":""},{"name":"AC Service & Recharge","price":"$$","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- CarMax (automotive - car-dealerships)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'CarMax', 'carmax', 'CarMax Team', 'info@carmax.com',
  '+1', NULL, 'https://www.carmax.com',
  COALESCE((SELECT id FROM categories WHERE slug='car-dealerships' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Richmond', 'VA', 'Richmond, VA, US',
  'America''s largest used-car retailer - no-haggle pricing and omni-channel buying since 1993.', 'CarMax is the largest used-vehicle retailer in the United States, operating 253 locations across 41 states as of 2025. Founded in 1993 as a Circuit City subsidiary and spun off as an independent public company in 2002, CarMax pioneered the no-haggle, fixed-price used-car buying model. The company offers an omni-channel experience - customers can browse online, arrange home delivery, or purchase entirely in store - and provides CarMax Auto Finance for on-the-spot financing.', 'https://www.google.com/s2/favicons?domain=carmax.com&sz=256',
  1993, '500+', 'https://www.linkedin.com/company/carmax', 'https://twitter.com/CarMax', 'https://www.facebook.com/CarMax',
  'company', 0, '["Used Car Dealer","No-Haggle Pricing","Auto Finance","Online & In-Store"]', 0, NULL,
  '$$', '[{"day":"Mon","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Tue","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Wed","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Thu","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Fri","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Sat","time":"9:00 AM - 9:00 PM","closed":false},{"day":"Sun","time":"12:00 PM - 7:00 PM","closed":false}]', '["free_estimates","credit_cards","financing","warranty","wheelchair"]', '[{"name":"Used Vehicle Purchase","price":"Varies","photo":""},{"name":"Vehicle Trade-In Appraisal","price":"Free","photo":""},{"name":"CarMax Auto Finance","price":"Varies","photo":""},{"name":"Extended Protection Plan","price":"Varies","photo":""},{"name":"Home Delivery","price":"Varies","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- Great Clips (beauty - hair-salons-2)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Great Clips', 'great-clips', 'Great Clips Team', 'info@greatclips.com',
  '+1', NULL, 'https://www.greatclips.com',
  COALESCE((SELECT id FROM categories WHERE slug='hair-salons-2' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Minneapolis', 'MN', 'Minneapolis, MN, US',
  'Affordable, no-appointment haircuts at over 4,500 locations across the US and Canada since 1982.', 'Great Clips is the world''s largest hair salon brand, with over 4,530 franchise locations across the United States and Canada. Founded in Minneapolis, Minnesota in 1982, the chain built its model around walk-in, no-appointment haircuts at accessible prices. Great Clips offers online check-in to reduce wait times and uses its Clip Notes system to remember each customer''s preferred cut. The chain employs approximately 30,000 stylists system-wide.', 'https://www.google.com/s2/favicons?domain=greatclips.com&sz=256',
  1982, '500+', 'https://www.linkedin.com/company/greatclips', 'https://twitter.com/greatclips', 'https://www.facebook.com/GreatClips/',
  'company', 0, '["Walk-In Haircuts","No Appointment Needed","Affordable Salon","Online Check-In"]', 0, NULL,
  '$', '[{"day":"Mon","time":"9:00 AM - 8:00 PM","closed":false},{"day":"Tue","time":"9:00 AM - 8:00 PM","closed":false},{"day":"Wed","time":"9:00 AM - 8:00 PM","closed":false},{"day":"Thu","time":"9:00 AM - 8:00 PM","closed":false},{"day":"Fri","time":"9:00 AM - 8:00 PM","closed":false},{"day":"Sat","time":"9:00 AM - 6:00 PM","closed":false},{"day":"Sun","time":"10:00 AM - 5:00 PM","closed":false}]', '["walk_ins","credit_cards","wifi","parking","wheelchair","gift_cards"]', '[{"name":"Adult Haircut","price":"$15 - $19","photo":""},{"name":"Senior Haircut","price":"$13 - $17","photo":""},{"name":"Child Haircut","price":"$13 - $16","photo":""},{"name":"Bang Trim","price":"$7 - $10","photo":""},{"name":"Beard Trim","price":"$7 - $10","photo":""},{"name":"Shampoo & Style","price":"$5 - $10","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- Gap (retail - clothing-stores)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Gap', 'gap', 'Gap Team', 'info@gap.com',
  '+1', NULL, 'https://www.gap.com',
  COALESCE((SELECT id FROM categories WHERE slug='clothing-stores' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'San Francisco', 'CA', 'San Francisco, CA, US',
  'American casual apparel for men, women, and kids - original denim and everyday essentials since 1969.', 'Gap is an iconic American clothing retailer founded by Donald and Doris Fisher in San Francisco in 1969, originally selling Levi''s jeans and records. The brand transitioned to private-label apparel in 1974 and is now recognized globally for casual wardrobe staples including denim, khakis, T-shirts, and activewear. As part of Gap Inc., which also operates Old Navy, Banana Republic, and Athleta, Gap operates thousands of stores worldwide and reported 82,000 employees across all brands as of 2025.', 'https://www.google.com/s2/favicons?domain=gap.com&sz=256',
  1969, '500+', 'https://www.linkedin.com/company/gap-inc-', 'https://twitter.com/gap', 'https://www.facebook.com/gap/',
  'company', 0, '["Casual Apparel","Denim & Basics","Men Women Kids","American Style"]', 0, NULL,
  '$', '[{"day":"Mon","time":"10:00 AM - 8:00 PM","closed":false},{"day":"Tue","time":"10:00 AM - 8:00 PM","closed":false},{"day":"Wed","time":"10:00 AM - 8:00 PM","closed":false},{"day":"Thu","time":"10:00 AM - 8:00 PM","closed":false},{"day":"Fri","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Sat","time":"10:00 AM - 9:00 PM","closed":false},{"day":"Sun","time":"11:00 AM - 6:00 PM","closed":false}]', '["in_store_pickup","curbside","returns_accepted","credit_cards","wifi","parking","wheelchair","gift_cards"]', '[{"name":"Denim Jeans (Men)","price":"$49.95 - $89.95","photo":""},{"name":"Denim Jeans (Women)","price":"$44.95 - $89.95","photo":""},{"name":"Classic Logo Hoodie","price":"$49.95 - $69.95","photo":""},{"name":"Everyday Soft T-Shirt","price":"$19.95 - $29.95","photo":""},{"name":"Kids Jeans","price":"$29.95 - $44.95","photo":""},{"name":"GapFit Activewear","price":"$34.95 - $64.95","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- Planet Fitness (fitness - gyms)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Planet Fitness', 'planet-fitness', 'Planet Fitness Team', 'info@planetfitness.com',
  '+1', NULL, 'https://www.planetfitness.com',
  COALESCE((SELECT id FROM categories WHERE slug='gyms' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Hampton', 'NH', 'Hampton, NH, US',
  'The Judgement Free Zone - affordable fitness for everyone with 2,700+ locations since 1992.', 'Planet Fitness is one of the largest fitness center franchisors in the United States, with over 2,715 clubs across North America, Central America, Spain, and Australia as of 2025. Founded in 1992 in Hampton, New Hampshire, the chain built its brand around the "Judgement Free Zone" philosophy - offering low-cost memberships, clean facilities, and a welcoming environment for gym newcomers and casual exercisers. Planet Fitness is publicly traded on the NYSE under the ticker PLNT.', 'https://www.google.com/s2/favicons?domain=planetfitness.com&sz=256',
  1992, '500+', 'https://www.linkedin.com/company/planet-fitness', 'https://twitter.com/PlanetFitness', 'https://www.facebook.com/planetfitness',
  'company', 0, '["Judgement Free Zone","Affordable Gym","Cardio & Strength","No Contract"]', 0, NULL,
  '$', '[{"day":"Mon","time":"5:00 AM - 12:00 AM","closed":false},{"day":"Tue","time":"5:00 AM - 12:00 AM","closed":false},{"day":"Wed","time":"5:00 AM - 12:00 AM","closed":false},{"day":"Thu","time":"5:00 AM - 12:00 AM","closed":false},{"day":"Fri","time":"5:00 AM - 9:00 PM","closed":false},{"day":"Sat","time":"7:00 AM - 8:00 PM","closed":false},{"day":"Sun","time":"7:00 AM - 8:00 PM","closed":false}]', '["free_trial","personal_training","showers","lockers","parking","wheelchair","credit_cards"]', '[{"name":"Classic Membership","price":"$15/month","photo":""},{"name":"Black Card Membership","price":"$24.99/month","photo":""},{"name":"Annual Fee","price":"$49/year","photo":""},{"name":"Free Fitness Training Sessions","price":"Included","photo":""},{"name":"Tanning (Black Card)","price":"Included","photo":""},{"name":"Massage Chairs (Black Card)","price":"Included","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- CorePower Yoga (fitness - yoga-studios)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'CorePower Yoga', 'corepower-yoga', 'CorePower Yoga Team', 'info@corepoweryoga.com',
  '+1', NULL, 'https://www.corepoweryoga.com',
  COALESCE((SELECT id FROM categories WHERE slug='yoga-studios' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Denver', 'CO', 'Denver, CO, US',
  'The largest yoga studio brand in the US - power yoga, sculpt, and hot yoga across 220+ locations.', 'CorePower Yoga is the largest yoga studio brand in the United States, with over 220 studios in 23 states as of 2024. Founded in Denver, Colorado in 2002, CorePower blends power yoga, ashtanga, and vinyasa traditions into a physically demanding, studio-heated practice environment. Class formats range from the foundational C2 flow to Yoga Sculpt - which adds weights and cardio - and CorePower StrengthX, a HIIT-inflected strength program. The brand also offers 200-hour and 300-hour teacher training certifications and a digital on-demand membership.', 'https://www.google.com/s2/favicons?domain=corepoweryoga.com&sz=256',
  2002, '500+', 'https://www.linkedin.com/company/corepower-yoga', 'https://twitter.com/CorePowerYoga', NULL,
  'company', 0, '["Power Yoga","Hot Yoga","Yoga Sculpt","Teacher Training","In-Studio & Online"]', 0, NULL,
  '$$$', '[{"day":"Mon","time":"6:00 AM - 9:00 PM","closed":false},{"day":"Tue","time":"6:00 AM - 9:00 PM","closed":false},{"day":"Wed","time":"6:00 AM - 9:00 PM","closed":false},{"day":"Thu","time":"6:00 AM - 9:00 PM","closed":false},{"day":"Fri","time":"6:00 AM - 9:00 PM","closed":false},{"day":"Sat","time":"7:00 AM - 8:00 PM","closed":false},{"day":"Sun","time":"7:00 AM - 8:00 PM","closed":false}]', '["free_trial","personal_training","showers","lockers","parking","wheelchair","credit_cards"]', '[{"name":"All-Access Monthly Membership","price":"$139 - $189/month","photo":""},{"name":"Online-Only Membership (On Demand)","price":"$19.99/month","photo":""},{"name":"5-Class Pack","price":"$109","photo":""},{"name":"10-Class Pack","price":"$199","photo":""},{"name":"Single Drop-In Class","price":"$23 - $28","photo":""},{"name":"200-Hour Teacher Training","price":"Varies","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- The Cheesecake Factory (food - american-restaurants)
INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location, tagline, description, logo_url,
  founded_year, team_size, linkedin, twitter, facebook,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'The Cheesecake Factory', 'the-cheesecake-factory', 'The Cheesecake Factory Team', 'info@thecheesecakefactory.com',
  '+1', NULL, 'https://www.thecheesecakefactory.com',
  COALESCE((SELECT id FROM categories WHERE slug='american-restaurants' LIMIT 1), @lb_sector), COALESCE((SELECT id FROM countries WHERE code='US' LIMIT 1), @fallback_country), 'Calabasas', 'CA', 'Calabasas, CA, US',
  'An eclectic American menu with 250+ items, legendary portions, and 30+ cheesecake flavors since 1978.', 'The Cheesecake Factory is an American casual-dining chain and cheesecake distributor headquartered in Calabasas, California. The restaurant brand opened its first full-service location in Beverly Hills in 1978, growing from a small Detroit bakery founded by Evelyn Overton in 1972. Known for its extensive menu of over 250 items - spanning pastas, burgers, seafood, steaks, and salads - and its signature lineup of more than 30 cheesecake flavors, the chain operates 218 branded restaurants and reported $3.58 billion in revenue in 2024.', 'https://www.google.com/s2/favicons?domain=thecheesecakefactory.com&sz=256',
  1978, '500+', 'https://www.linkedin.com/company/lifeatcheesecake', 'https://twitter.com/Cheesecake', NULL,
  'company', 0, '["American Casual Dining","250+ Menu Items","Signature Cheesecakes","Large Portions"]', 0, NULL,
  '$$$', '[{"day":"Mon","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Tue","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Wed","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Thu","time":"11:00 AM - 10:00 PM","closed":false},{"day":"Fri","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Sat","time":"10:00 AM - 11:00 PM","closed":false},{"day":"Sun","time":"10:00 AM - 10:00 PM","closed":false}]', '["takeout","delivery","credit_cards","wifi","vegetarian","outdoor_seating","reservations","parking","wheelchair"]', '[{"name":"Avocado Eggrolls","price":"$16.95","photo":""},{"name":"Chicken Madeira","price":"$26.95","photo":""},{"name":"Louisiana Chicken Pasta","price":"$23.95","photo":""},{"name":"Fresh Strawberry Cheesecake (slice)","price":"$9.95 - $11.95","photo":""},{"name":"Godiva Chocolate Cheesecake (slice)","price":"$9.95 - $11.95","photo":""},{"name":"Whole 10-inch Cheesecake","price":"$65.95 - $72.95","photo":""},{"name":"Factory Chopped Salad","price":"$16.95","photo":""},{"name":"Pasta Da Vinci","price":"$22.95","photo":""}]', '[]', '[]', NULL, NULL,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();
