-- ============================================================================
-- Seed: Software & SaaS — ~220 real companies for the scraper queue.
-- ON DUPLICATE KEY UPDATE id=id makes this re-runnable / idempotent.
-- Run in phpMyAdmin → SQL tab.
-- ============================================================================

INSERT INTO scrape_jobs (slug, company_name, website, category_l1, category_slug, status)
VALUES

-- ─── Project management & productivity ────────────────────────────────────
('notion',             'Notion',             'https://www.notion.so',              'software-and-saas', 'project-management-software', 'queued'),
('linear',             'Linear',             'https://linear.app',                 'software-and-saas', 'project-management-software', 'queued'),
('asana',              'Asana',              'https://asana.com',                  'software-and-saas', 'project-management-software', 'queued'),
('monday-com',         'Monday.com',         'https://monday.com',                 'software-and-saas', 'project-management-software', 'queued'),
('clickup',            'ClickUp',            'https://clickup.com',                'software-and-saas', 'project-management-software', 'queued'),
('coda',               'Coda',               'https://coda.io',                    'software-and-saas', 'project-management-software', 'queued'),
('airtable',           'Airtable',           'https://www.airtable.com',           'software-and-saas', 'project-management-software', 'queued'),
('trello',             'Trello',             'https://trello.com',                 'software-and-saas', 'project-management-software', 'queued'),
('basecamp',           'Basecamp',           'https://basecamp.com',               'software-and-saas', 'project-management-software', 'queued'),
('jira',               'Atlassian Jira',     'https://www.atlassian.com/software/jira', 'software-and-saas', 'project-management-software', 'queued'),
('confluence',         'Atlassian Confluence', 'https://www.atlassian.com/software/confluence', 'software-and-saas', 'wiki-software', 'queued'),
('clickup',            'ClickUp',            'https://clickup.com',                'software-and-saas', 'project-management-software', 'queued'),
('wrike',              'Wrike',              'https://www.wrike.com',              'software-and-saas', 'project-management-software', 'queued'),
('smartsheet',         'Smartsheet',         'https://www.smartsheet.com',         'software-and-saas', 'project-management-software', 'queued'),
('teamwork',           'Teamwork',           'https://www.teamwork.com',           'software-and-saas', 'project-management-software', 'queued'),
('hive',               'Hive',               'https://hive.com',                   'software-and-saas', 'project-management-software', 'queued'),
('proofhub',           'ProofHub',           'https://www.proofhub.com',           'software-and-saas', 'project-management-software', 'queued'),
('todoist',            'Todoist',            'https://todoist.com',                'software-and-saas', 'task-management', 'queued'),
('things-3',           'Things',             'https://culturedcode.com/things',    'software-and-saas', 'task-management', 'queued'),
('omnifocus',          'OmniFocus',          'https://www.omnigroup.com/omnifocus','software-and-saas', 'task-management', 'queued'),
('tick-tick',          'TickTick',           'https://ticktick.com',               'software-and-saas', 'task-management', 'queued'),
('any-do',             'Any.do',             'https://www.any.do',                 'software-and-saas', 'task-management', 'queued'),
('height-app',         'Height',             'https://height.app',                 'software-and-saas', 'project-management-software', 'queued'),
('shortcut',           'Shortcut',           'https://www.shortcut.com',           'software-and-saas', 'project-management-software', 'queued'),

-- ─── Communication & collaboration ────────────────────────────────────────
('slack',              'Slack',              'https://slack.com',                  'software-and-saas', 'team-chat-software', 'queued'),
('discord',            'Discord',            'https://discord.com',                'software-and-saas', 'community-chat', 'queued'),
('microsoft-teams',    'Microsoft Teams',    'https://www.microsoft.com/microsoft-teams', 'software-and-saas', 'team-chat-software', 'queued'),
('zoom',               'Zoom',               'https://zoom.us',                    'software-and-saas', 'video-conferencing', 'queued'),
('webex',              'Webex',              'https://www.webex.com',              'software-and-saas', 'video-conferencing', 'queued'),
('google-meet',        'Google Meet',        'https://meet.google.com',            'software-and-saas', 'video-conferencing', 'queued'),
('loom',               'Loom',               'https://www.loom.com',               'software-and-saas', 'screen-recording-software', 'queued'),
('vidyard',            'Vidyard',            'https://www.vidyard.com',            'software-and-saas', 'screen-recording-software', 'queued'),
('whereby',            'Whereby',            'https://whereby.com',                'software-and-saas', 'video-conferencing', 'queued'),
('gotomeeting',        'GoTo Meeting',       'https://www.goto.com/meeting',       'software-and-saas', 'video-conferencing', 'queued'),
('twist',              'Twist',              'https://twist.com',                  'software-and-saas', 'team-chat-software', 'queued'),
('flock',              'Flock',              'https://www.flock.com',              'software-and-saas', 'team-chat-software', 'queued'),
('chanty',             'Chanty',             'https://www.chanty.com',             'software-and-saas', 'team-chat-software', 'queued'),
('rocket-chat',        'Rocket.Chat',        'https://www.rocket.chat',            'software-and-saas', 'team-chat-software', 'queued'),
('mattermost',         'Mattermost',         'https://mattermost.com',             'software-and-saas', 'team-chat-software', 'queued'),

-- ─── Design & creative ────────────────────────────────────────────────────
('figma',              'Figma',              'https://www.figma.com',              'software-and-saas', 'design-software', 'queued'),
('sketch',             'Sketch',             'https://www.sketch.com',             'software-and-saas', 'design-software', 'queued'),
('canva',              'Canva',              'https://www.canva.com',              'software-and-saas', 'design-software', 'queued'),
('adobe-creative-cloud','Adobe Creative Cloud', 'https://www.adobe.com/creativecloud.html', 'software-and-saas', 'design-software', 'queued'),
('invision',           'InVision',           'https://www.invisionapp.com',        'software-and-saas', 'design-software', 'queued'),
('framer',             'Framer',             'https://www.framer.com',             'software-and-saas', 'design-software', 'queued'),
('penpot',             'Penpot',             'https://penpot.app',                 'software-and-saas', 'design-software', 'queued'),
('miro',               'Miro',               'https://miro.com',                   'software-and-saas', 'whiteboard-software', 'queued'),
('mural',              'Mural',              'https://www.mural.co',               'software-and-saas', 'whiteboard-software', 'queued'),
('whimsical',          'Whimsical',          'https://whimsical.com',              'software-and-saas', 'whiteboard-software', 'queued'),
('excalidraw',         'Excalidraw',         'https://excalidraw.com',             'software-and-saas', 'whiteboard-software', 'queued'),
('lucidchart',         'Lucidchart',         'https://www.lucidchart.com',         'software-and-saas', 'diagram-software', 'queued'),
('lucidspark',         'Lucidspark',         'https://www.lucidspark.com',         'software-and-saas', 'whiteboard-software', 'queued'),
('balsamiq',           'Balsamiq',           'https://balsamiq.com',               'software-and-saas', 'wireframe-software', 'queued'),
('marvel-app',         'Marvel',             'https://marvelapp.com',              'software-and-saas', 'prototyping-software', 'queued'),
('protopie',           'ProtoPie',           'https://www.protopie.io',            'software-and-saas', 'prototyping-software', 'queued'),
('zeplin',             'Zeplin',             'https://zeplin.io',                  'software-and-saas', 'design-handoff', 'queued'),
('abstract',           'Abstract',           'https://www.abstract.com',           'software-and-saas', 'design-version-control', 'queued'),

-- ─── Email & marketing automation ─────────────────────────────────────────
('mailchimp',          'Mailchimp',          'https://mailchimp.com',              'software-and-saas', 'email-marketing-software', 'queued'),
('klaviyo',            'Klaviyo',            'https://www.klaviyo.com',            'software-and-saas', 'email-marketing-software', 'queued'),
('convertkit',         'ConvertKit',         'https://convertkit.com',             'software-and-saas', 'email-marketing-software', 'queued'),
('beehiiv',            'Beehiiv',            'https://www.beehiiv.com',            'software-and-saas', 'newsletter-software', 'queued'),
('substack',           'Substack',           'https://substack.com',               'software-and-saas', 'newsletter-software', 'queued'),
('aweber',             'AWeber',             'https://www.aweber.com',             'software-and-saas', 'email-marketing-software', 'queued'),
('campaign-monitor',   'Campaign Monitor',   'https://www.campaignmonitor.com',    'software-and-saas', 'email-marketing-software', 'queued'),
('getresponse',        'GetResponse',        'https://www.getresponse.com',        'software-and-saas', 'email-marketing-software', 'queued'),
('drip',               'Drip',               'https://www.drip.com',               'software-and-saas', 'email-marketing-software', 'queued'),
('sendgrid',           'SendGrid',           'https://sendgrid.com',               'software-and-saas', 'transactional-email', 'queued'),
('postmark',           'Postmark',           'https://postmarkapp.com',            'software-and-saas', 'transactional-email', 'queued'),
('mailgun',            'Mailgun',            'https://www.mailgun.com',            'software-and-saas', 'transactional-email', 'queued'),
('resend-com',         'Resend',             'https://resend.com',                 'software-and-saas', 'transactional-email', 'queued'),
('loops-so',           'Loops',              'https://loops.so',                   'software-and-saas', 'transactional-email', 'queued'),
('customer-io',        'Customer.io',        'https://customer.io',                'software-and-saas', 'customer-engagement', 'queued'),
('iterable',           'Iterable',           'https://iterable.com',               'software-and-saas', 'customer-engagement', 'queued'),
('braze',              'Braze',              'https://www.braze.com',              'software-and-saas', 'customer-engagement', 'queued'),
('omnisend',           'Omnisend',           'https://www.omnisend.com',           'software-and-saas', 'email-marketing-software', 'queued'),
('moosend',            'Moosend',            'https://moosend.com',                'software-and-saas', 'email-marketing-software', 'queued'),
('flodesk',            'Flodesk',            'https://flodesk.com',                'software-and-saas', 'email-marketing-software', 'queued'),

-- ─── CRM ──────────────────────────────────────────────────────────────────
('salesforce',         'Salesforce',         'https://www.salesforce.com',         'software-and-saas', 'crm-software', 'queued'),
('hubspot',            'HubSpot',            'https://www.hubspot.com',            'software-and-saas', 'crm-software', 'queued'),
('pipedrive',          'Pipedrive',          'https://www.pipedrive.com',          'software-and-saas', 'crm-software', 'queued'),
('zoho-crm',           'Zoho CRM',           'https://www.zoho.com/crm',           'software-and-saas', 'crm-software', 'queued'),
('freshsales',         'Freshsales',         'https://www.freshworks.com/crm',     'software-and-saas', 'crm-software', 'queued'),
('attio',              'Attio',              'https://attio.com',                  'software-and-saas', 'crm-software', 'queued'),
('folk',               'Folk',               'https://www.folk.app',               'software-and-saas', 'crm-software', 'queued'),
('close-com',          'Close',              'https://close.com',                  'software-and-saas', 'crm-software', 'queued'),
('copper',             'Copper',             'https://www.copper.com',             'software-and-saas', 'crm-software', 'queued'),
('insightly',          'Insightly',          'https://www.insightly.com',          'software-and-saas', 'crm-software', 'queued'),
('keap',               'Keap',               'https://keap.com',                   'software-and-saas', 'crm-software', 'queued'),
('nimble-crm',         'Nimble',             'https://www.nimble.com',             'software-and-saas', 'crm-software', 'queued'),

-- ─── Dev tools ────────────────────────────────────────────────────────────
('github',             'GitHub',             'https://github.com',                 'software-and-saas', 'code-hosting', 'queued'),
('gitlab',             'GitLab',             'https://about.gitlab.com',           'software-and-saas', 'code-hosting', 'queued'),
('bitbucket',          'Bitbucket',          'https://bitbucket.org',              'software-and-saas', 'code-hosting', 'queued'),
('sentry',             'Sentry',             'https://sentry.io',                  'software-and-saas', 'error-monitoring', 'queued'),
('datadog',            'Datadog',            'https://www.datadoghq.com',          'software-and-saas', 'monitoring', 'queued'),
('new-relic',          'New Relic',          'https://newrelic.com',               'software-and-saas', 'monitoring', 'queued'),
('honeycomb',          'Honeycomb',          'https://www.honeycomb.io',           'software-and-saas', 'observability', 'queued'),
('grafana',            'Grafana',            'https://grafana.com',                'software-and-saas', 'monitoring', 'queued'),
('rollbar',            'Rollbar',            'https://rollbar.com',                'software-and-saas', 'error-monitoring', 'queued'),
('bugsnag',            'BugSnag',            'https://www.bugsnag.com',            'software-and-saas', 'error-monitoring', 'queued'),
('postman',            'Postman',            'https://www.postman.com',            'software-and-saas', 'api-tools', 'queued'),
('insomnia',           'Insomnia',           'https://insomnia.rest',              'software-and-saas', 'api-tools', 'queued'),
('hoppscotch',         'Hoppscotch',         'https://hoppscotch.io',              'software-and-saas', 'api-tools', 'queued'),
('mockoon',            'Mockoon',            'https://mockoon.com',                'software-and-saas', 'api-tools', 'queued'),
('codacy',             'Codacy',             'https://www.codacy.com',             'software-and-saas', 'code-quality', 'queued'),
('snyk',               'Snyk',               'https://snyk.io',                    'software-and-saas', 'security-software', 'queued'),
('jetbrains',          'JetBrains',          'https://www.jetbrains.com',          'software-and-saas', 'ide-software', 'queued'),
('codacy',             'Codacy',             'https://www.codacy.com',             'software-and-saas', 'code-quality', 'queued'),

-- ─── Hosting / deploy / infra ─────────────────────────────────────────────
('vercel',             'Vercel',             'https://vercel.com',                 'software-and-saas', 'hosting-platform', 'queued'),
('netlify',            'Netlify',            'https://www.netlify.com',            'software-and-saas', 'hosting-platform', 'queued'),
('cloudflare-pages',   'Cloudflare Pages',   'https://pages.cloudflare.com',       'software-and-saas', 'hosting-platform', 'queued'),
('railway',            'Railway',            'https://railway.app',                'software-and-saas', 'hosting-platform', 'queued'),
('render',             'Render',             'https://render.com',                 'software-and-saas', 'hosting-platform', 'queued'),
('fly-io',             'Fly.io',             'https://fly.io',                     'software-and-saas', 'hosting-platform', 'queued'),
('heroku',             'Heroku',             'https://www.heroku.com',             'software-and-saas', 'hosting-platform', 'queued'),
('digitalocean',       'DigitalOcean',       'https://www.digitalocean.com',       'software-and-saas', 'cloud-hosting', 'queued'),
('linode',             'Linode',             'https://www.linode.com',             'software-and-saas', 'cloud-hosting', 'queued'),
('vultr',              'Vultr',              'https://www.vultr.com',              'software-and-saas', 'cloud-hosting', 'queued'),
('supabase',           'Supabase',           'https://supabase.com',               'software-and-saas', 'baas', 'queued'),
('firebase',           'Firebase',           'https://firebase.google.com',        'software-and-saas', 'baas', 'queued'),
('appwrite',           'Appwrite',           'https://appwrite.io',                'software-and-saas', 'baas', 'queued'),
('pocketbase',         'PocketBase',         'https://pocketbase.io',              'software-and-saas', 'baas', 'queued'),
('nhost',              'Nhost',              'https://nhost.io',                   'software-and-saas', 'baas', 'queued'),

-- ─── Databases / data ─────────────────────────────────────────────────────
('planetscale',        'PlanetScale',        'https://planetscale.com',            'software-and-saas', 'database-as-a-service', 'queued'),
('neon-tech',          'Neon',               'https://neon.tech',                  'software-and-saas', 'database-as-a-service', 'queued'),
('mongodb-atlas',      'MongoDB Atlas',      'https://www.mongodb.com/atlas',      'software-and-saas', 'database-as-a-service', 'queued'),
('cockroachdb',        'CockroachDB',        'https://www.cockroachlabs.com',      'software-and-saas', 'database-as-a-service', 'queued'),
('tigerbeetle',        'TigerBeetle',        'https://tigerbeetle.com',            'software-and-saas', 'database-as-a-service', 'queued'),
('redis',              'Redis',              'https://redis.io',                   'software-and-saas', 'database-as-a-service', 'queued'),
('upstash',            'Upstash',            'https://upstash.com',                'software-and-saas', 'database-as-a-service', 'queued'),
('clickhouse',         'ClickHouse',         'https://clickhouse.com',             'software-and-saas', 'database-as-a-service', 'queued'),
('snowflake',          'Snowflake',          'https://www.snowflake.com',          'software-and-saas', 'data-warehouse', 'queued'),
('databricks',         'Databricks',         'https://www.databricks.com',         'software-and-saas', 'data-platform', 'queued'),
('bigquery',           'Google BigQuery',    'https://cloud.google.com/bigquery',  'software-and-saas', 'data-warehouse', 'queued'),

-- ─── Stripe & payments ────────────────────────────────────────────────────
('stripe',             'Stripe',             'https://stripe.com',                 'software-and-saas', 'payments-software', 'queued'),
('square',             'Square',             'https://squareup.com',               'software-and-saas', 'payments-software', 'queued'),
('paypal',             'PayPal',             'https://www.paypal.com',             'software-and-saas', 'payments-software', 'queued'),
('adyen',              'Adyen',              'https://www.adyen.com',              'software-and-saas', 'payments-software', 'queued'),
('checkout-com',       'Checkout.com',       'https://www.checkout.com',           'software-and-saas', 'payments-software', 'queued'),
('paddle',             'Paddle',             'https://www.paddle.com',             'software-and-saas', 'payments-software', 'queued'),
('lemon-squeezy',      'Lemon Squeezy',      'https://www.lemonsqueezy.com',       'software-and-saas', 'payments-software', 'queued'),
('mollie',             'Mollie',             'https://www.mollie.com',             'software-and-saas', 'payments-software', 'queued'),
('razorpay',           'Razorpay',           'https://razorpay.com',               'software-and-saas', 'payments-software', 'queued'),
('paystack',           'Paystack',           'https://paystack.com',               'software-and-saas', 'payments-software', 'queued'),
('chargebee',          'Chargebee',          'https://www.chargebee.com',          'software-and-saas', 'subscription-billing', 'queued'),
('recurly',            'Recurly',            'https://recurly.com',                'software-and-saas', 'subscription-billing', 'queued'),
('zuora',              'Zuora',              'https://www.zuora.com',              'software-and-saas', 'subscription-billing', 'queued'),
('stripe-billing',     'Stripe Billing',     'https://stripe.com/billing',         'software-and-saas', 'subscription-billing', 'queued'),

-- ─── E-commerce ───────────────────────────────────────────────────────────
('shopify',            'Shopify',            'https://www.shopify.com',            'software-and-saas', 'ecommerce-platform', 'queued'),
('bigcommerce',        'BigCommerce',        'https://www.bigcommerce.com',        'software-and-saas', 'ecommerce-platform', 'queued'),
('woocommerce',        'WooCommerce',        'https://woocommerce.com',            'software-and-saas', 'ecommerce-platform', 'queued'),
('squarespace',        'Squarespace',        'https://www.squarespace.com',        'software-and-saas', 'website-builder', 'queued'),
('wix',                'Wix',                'https://www.wix.com',                'software-and-saas', 'website-builder', 'queued'),
('webflow',            'Webflow',            'https://webflow.com',                'software-and-saas', 'website-builder', 'queued'),
('wordpress-com',      'WordPress.com',      'https://wordpress.com',              'software-and-saas', 'website-builder', 'queued'),
('weebly',             'Weebly',             'https://www.weebly.com',             'software-and-saas', 'website-builder', 'queued'),
('carrd',              'Carrd',              'https://carrd.co',                   'software-and-saas', 'website-builder', 'queued'),
('strikingly',         'Strikingly',         'https://www.strikingly.com',         'software-and-saas', 'website-builder', 'queued'),

-- ─── Customer support / helpdesk ──────────────────────────────────────────
('intercom',           'Intercom',           'https://www.intercom.com',           'software-and-saas', 'customer-support-software', 'queued'),
('zendesk',            'Zendesk',            'https://www.zendesk.com',            'software-and-saas', 'customer-support-software', 'queued'),
('freshdesk',          'Freshdesk',          'https://www.freshworks.com/freshdesk', 'software-and-saas', 'customer-support-software', 'queued'),
('help-scout',         'Help Scout',         'https://www.helpscout.com',          'software-and-saas', 'customer-support-software', 'queued'),
('crisp-chat',         'Crisp',              'https://crisp.chat',                 'software-and-saas', 'customer-support-software', 'queued'),
('frontapp',           'Front',              'https://front.com',                  'software-and-saas', 'customer-support-software', 'queued'),
('gorgias',            'Gorgias',            'https://www.gorgias.com',            'software-and-saas', 'customer-support-software', 'queued'),
('kustomer',           'Kustomer',           'https://www.kustomer.com',           'software-and-saas', 'customer-support-software', 'queued'),
('hiver',              'Hiver',              'https://hiverhq.com',                'software-and-saas', 'customer-support-software', 'queued'),
('plain-com',          'Plain',              'https://www.plain.com',              'software-and-saas', 'customer-support-software', 'queued'),

-- ─── HR / payroll ─────────────────────────────────────────────────────────
('workday',            'Workday',            'https://www.workday.com',            'software-and-saas', 'hr-software', 'queued'),
('bamboohr',           'BambooHR',           'https://www.bamboohr.com',           'software-and-saas', 'hr-software', 'queued'),
('gusto',              'Gusto',              'https://gusto.com',                  'software-and-saas', 'payroll-software', 'queued'),
('rippling',           'Rippling',           'https://www.rippling.com',           'software-and-saas', 'hr-software', 'queued'),
('deel',               'Deel',               'https://www.deel.com',               'software-and-saas', 'global-payroll', 'queued'),
('remote-com',         'Remote',             'https://remote.com',                 'software-and-saas', 'global-payroll', 'queued'),
('oyster',             'Oyster',             'https://www.oysterhr.com',           'software-and-saas', 'global-payroll', 'queued'),
('papaya-global',      'Papaya Global',      'https://www.papayaglobal.com',       'software-and-saas', 'global-payroll', 'queued'),
('multiplier',         'Multiplier',         'https://www.usemultiplier.com',      'software-and-saas', 'global-payroll', 'queued'),
('lever',              'Lever',              'https://www.lever.co',               'software-and-saas', 'recruiting-software', 'queued'),
('greenhouse',         'Greenhouse',         'https://www.greenhouse.io',          'software-and-saas', 'recruiting-software', 'queued'),
('ashby',              'Ashby',              'https://www.ashbyhq.com',            'software-and-saas', 'recruiting-software', 'queued'),
('workable',           'Workable',           'https://www.workable.com',           'software-and-saas', 'recruiting-software', 'queued'),

-- ─── Finance / accounting ─────────────────────────────────────────────────
('quickbooks',         'QuickBooks',         'https://quickbooks.intuit.com',      'software-and-saas', 'accounting-software', 'queued'),
('xero',               'Xero',               'https://www.xero.com',               'software-and-saas', 'accounting-software', 'queued'),
('freshbooks',         'FreshBooks',         'https://www.freshbooks.com',         'software-and-saas', 'accounting-software', 'queued'),
('wave-financial',     'Wave',               'https://www.waveapps.com',           'software-and-saas', 'accounting-software', 'queued'),
('zoho-books',         'Zoho Books',         'https://www.zoho.com/books',         'software-and-saas', 'accounting-software', 'queued'),
('pilot-bookkeeping',  'Pilot',              'https://pilot.com',                  'software-and-saas', 'bookkeeping-service', 'queued'),
('bench-accounting',   'Bench',              'https://www.bench.co',               'software-and-saas', 'bookkeeping-service', 'queued'),
('brex',               'Brex',               'https://www.brex.com',               'software-and-saas', 'corporate-card', 'queued'),
('ramp',               'Ramp',               'https://ramp.com',                   'software-and-saas', 'corporate-card', 'queued'),
('mercury',            'Mercury',            'https://mercury.com',                'software-and-saas', 'business-banking', 'queued'),
('relay-fi',           'Relay',              'https://relayfi.com',                'software-and-saas', 'business-banking', 'queued'),

-- ─── Analytics ────────────────────────────────────────────────────────────
('mixpanel',           'Mixpanel',           'https://mixpanel.com',               'software-and-saas', 'product-analytics', 'queued'),
('amplitude',          'Amplitude',          'https://amplitude.com',              'software-and-saas', 'product-analytics', 'queued'),
('heap-io',            'Heap',               'https://heap.io',                    'software-and-saas', 'product-analytics', 'queued'),
('posthog',            'PostHog',            'https://posthog.com',                'software-and-saas', 'product-analytics', 'queued'),
('june-so',            'June',               'https://www.june.so',                'software-and-saas', 'product-analytics', 'queued'),
('plausible',          'Plausible',          'https://plausible.io',               'software-and-saas', 'web-analytics', 'queued'),
('fathom-analytics',   'Fathom Analytics',   'https://usefathom.com',              'software-and-saas', 'web-analytics', 'queued'),
('simple-analytics',   'Simple Analytics',   'https://www.simpleanalytics.com',    'software-and-saas', 'web-analytics', 'queued'),
('matomo',             'Matomo',             'https://matomo.org',                 'software-and-saas', 'web-analytics', 'queued'),
('hotjar',             'Hotjar',             'https://www.hotjar.com',             'software-and-saas', 'session-replay', 'queued'),
('fullstory',          'FullStory',          'https://www.fullstory.com',          'software-and-saas', 'session-replay', 'queued'),
('logrocket',          'LogRocket',          'https://logrocket.com',              'software-and-saas', 'session-replay', 'queued'),
('microsoft-clarity',  'Microsoft Clarity',  'https://clarity.microsoft.com',      'software-and-saas', 'session-replay', 'queued'),

-- ─── Authentication & security ────────────────────────────────────────────
('auth0',              'Auth0',              'https://auth0.com',                  'software-and-saas', 'authentication-software', 'queued'),
('clerk-com',          'Clerk',              'https://clerk.com',                  'software-and-saas', 'authentication-software', 'queued'),
('workos',             'WorkOS',             'https://workos.com',                 'software-and-saas', 'authentication-software', 'queued'),
('okta',               'Okta',               'https://www.okta.com',               'software-and-saas', 'identity-software', 'queued'),
('onelogin',           'OneLogin',           'https://www.onelogin.com',           'software-and-saas', 'identity-software', 'queued'),
('1password',          '1Password',          'https://1password.com',              'software-and-saas', 'password-manager', 'queued'),
('lastpass',           'LastPass',           'https://www.lastpass.com',           'software-and-saas', 'password-manager', 'queued'),
('dashlane',           'Dashlane',           'https://www.dashlane.com',           'software-and-saas', 'password-manager', 'queued'),
('bitwarden',          'Bitwarden',          'https://bitwarden.com',              'software-and-saas', 'password-manager', 'queued'),
('vanta',              'Vanta',              'https://www.vanta.com',              'software-and-saas', 'compliance-software', 'queued'),
('drata',              'Drata',              'https://drata.com',                  'software-and-saas', 'compliance-software', 'queued'),
('secureframe',        'Secureframe',        'https://secureframe.com',            'software-and-saas', 'compliance-software', 'queued'),

-- ─── No-code / low-code ──────────────────────────────────────────────────
('bubble',             'Bubble',             'https://bubble.io',                  'software-and-saas', 'no-code-platform', 'queued'),
('softr',              'Softr',              'https://www.softr.io',               'software-and-saas', 'no-code-platform', 'queued'),
('glide',              'Glide',              'https://www.glideapps.com',          'software-and-saas', 'no-code-platform', 'queued'),
('zapier',             'Zapier',             'https://zapier.com',                 'software-and-saas', 'workflow-automation', 'queued'),
('make-com',           'Make',               'https://www.make.com',               'software-and-saas', 'workflow-automation', 'queued'),
('n8n',                'n8n',                'https://n8n.io',                     'software-and-saas', 'workflow-automation', 'queued'),
('pipedream',          'Pipedream',          'https://pipedream.com',              'software-and-saas', 'workflow-automation', 'queued'),
('tray-io',            'Tray.io',            'https://tray.io',                    'software-and-saas', 'integration-platform', 'queued'),
('workato',            'Workato',            'https://www.workato.com',            'software-and-saas', 'integration-platform', 'queued'),
('boomi',              'Boomi',              'https://boomi.com',                  'software-and-saas', 'integration-platform', 'queued'),
('mulesoft',           'MuleSoft',           'https://www.mulesoft.com',           'software-and-saas', 'integration-platform', 'queued'),

-- ─── File storage / collaboration ────────────────────────────────────────
('dropbox',            'Dropbox',            'https://www.dropbox.com',            'software-and-saas', 'file-storage', 'queued'),
('google-drive',       'Google Drive',       'https://www.google.com/drive',       'software-and-saas', 'file-storage', 'queued'),
('onedrive',           'Microsoft OneDrive', 'https://www.microsoft.com/en/microsoft-365/onedrive', 'software-and-saas', 'file-storage', 'queued'),
('box',                'Box',                'https://www.box.com',                'software-and-saas', 'file-storage', 'queued'),
('sync-com',           'Sync.com',           'https://www.sync.com',               'software-and-saas', 'file-storage', 'queued'),
('pcloud',             'pCloud',             'https://www.pcloud.com',             'software-and-saas', 'file-storage', 'queued'),

-- ─── Scheduling / calendar ───────────────────────────────────────────────
('calendly',           'Calendly',           'https://calendly.com',               'software-and-saas', 'scheduling-software', 'queued'),
('cal-com',            'Cal.com',            'https://cal.com',                    'software-and-saas', 'scheduling-software', 'queued'),
('savvycal',           'SavvyCal',           'https://savvycal.com',               'software-and-saas', 'scheduling-software', 'queued'),
('youcanbookme',       'YouCanBook.me',      'https://youcanbook.me',              'software-and-saas', 'scheduling-software', 'queued'),
('acuity-scheduling',  'Acuity Scheduling',  'https://acuityscheduling.com',       'software-and-saas', 'scheduling-software', 'queued'),
('doodle',             'Doodle',             'https://doodle.com',                 'software-and-saas', 'scheduling-software', 'queued'),

-- ─── Survey / feedback ───────────────────────────────────────────────────
('typeform',           'Typeform',           'https://www.typeform.com',           'software-and-saas', 'survey-software', 'queued'),
('surveymonkey',       'SurveyMonkey',       'https://www.surveymonkey.com',       'software-and-saas', 'survey-software', 'queued'),
('tally-so',           'Tally',              'https://tally.so',                   'software-and-saas', 'survey-software', 'queued'),
('formspark',          'Formspark',          'https://formspark.io',               'software-and-saas', 'survey-software', 'queued'),
('jotform',            'Jotform',            'https://www.jotform.com',            'software-and-saas', 'survey-software', 'queued'),
('forms-google',       'Google Forms',       'https://forms.google.com',           'software-and-saas', 'survey-software', 'queued'),
('hotjar',             'Hotjar',             'https://www.hotjar.com',             'software-and-saas', 'feedback-software', 'queued'),
('canny',              'Canny',              'https://canny.io',                   'software-and-saas', 'feedback-software', 'queued'),
('productboard',       'Productboard',       'https://www.productboard.com',       'software-and-saas', 'product-management', 'queued')

ON DUPLICATE KEY UPDATE id = id;
