-- ============================================================
-- InfoWebWorld - REAL local businesses (OpenStreetMap)
-- Generated by scripts/gen-local-businesses-sql.mjs  —  25 businesses
-- Source: © OpenStreetMap contributors (ODbL). Show attribution on-site.
--
-- All data real (name/website/phone/address/coords/hours/amenities from OSM).
-- Unknown fields left empty — owners complete them via the claim → edit flow.
-- listing_mode='company', status='pending' (NOT live), user_id NULL (claimable).
-- Review in /iww-hq/submissions, then run the GO-LIVE block at the bottom.
-- Re-runnable: the DELETE below clears any prior run of this seed.
-- ============================================================

SET @free_plan := (SELECT id FROM plans WHERE is_active = 1 ORDER BY price ASC LIMIT 1);
SET @lb_sector := (SELECT id FROM categories WHERE slug = 'local-businesses' AND level = 1 LIMIT 1);
SET @co_US := (SELECT id FROM countries WHERE code = 'US' LIMIT 1);

DELETE FROM submissions WHERE listing_mode = 'company' AND slug IN ('pedros-new-york', 'trudys-ice-cream-new-york', 'little-alley-new-york', 'nha-trang-one-new-york', 'le-monde-new-york', 'carmines-pizzeria-new-york', 'sol-et-soleil-new-york', 'hard-rock-cafe-new-york', 'freemans-new-york', 'aurora-new-york', 'tick-tock-diner-new-york', 'giovanni-new-york', 'vinegar-hill-house-new-york', 'juniors-new-york', 'diner-new-york', 'ako-new-york', 'joes-pizza-new-york', 'momo-sushi-new-york', 'lombardis-pizza-new-york', 'moc-mac-new-york', 'toms-restaurant-new-york', 'the-river-cafe-new-york', 'bills-townhouse-new-york', 'four-seasons-new-york', 'smith-wollensky-new-york');

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Pedro''s', 'pedros-new-york', '', '', '', '+1-718-797-2851', 'https://pedrosbrooklyn.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'mexican-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '73 Jay Street, New York, NY',
  'Mexican restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=pedrosbrooklyn.com&sz=256', NULL, NULL,
  'company', 0, '["Mexican","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Tue","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Wed","time":"12:00 PM - 10:00 PM","closed":false}]', '["vegetarian","credit_cards"]', NULL, NULL, NULL, 40.7025302, -73.9865515,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Trudy''s Ice Cream', 'trudys-ice-cream-new-york', '', '', '', '+1-646-649-3612', 'https://trudysicecream.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '975 Columbus Avenue, New York, NY',
  'Dessert restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=trudysicecream.com&sz=256', NULL, NULL,
  'company', 0, '["Dessert","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"12:00 PM - 9:00 PM","closed":false},{"day":"Tue","time":"12:00 PM - 9:00 PM","closed":false},{"day":"Wed","time":"12:00 PM - 9:00 PM","closed":false},{"day":"Thu","time":"12:00 PM - 9:00 PM","closed":false},{"day":"Fri","time":"12:00 PM - 9:00 PM","closed":false},{"day":"Sat","time":"11:00 AM - 9:00 PM","closed":false},{"day":"Sun","time":"11:00 AM - 9:00 PM","closed":false}]', NULL, NULL, NULL, NULL, 40.8003773, -73.9618056,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Little Alley', 'little-alley-new-york', '', '', '', '+1-646-998-3976', 'https://www.littlealley.nyc',
  COALESCE((SELECT id FROM categories WHERE slug = 'chinese-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '550 3rd Avenue, New York, NY',
  'Chinese restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=littlealley.nyc&sz=256', NULL, NULL,
  'company', 0, '["Chinese","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"11:30 AM - 3:00 PM","closed":false},{"day":"Tue","time":"11:30 AM - 3:00 PM","closed":false},{"day":"Wed","time":"11:30 AM - 3:00 PM","closed":false},{"day":"Thu","time":"11:30 AM - 3:00 PM","closed":false},{"day":"Fri","time":"11:30 AM - 3:00 PM","closed":false},{"day":"Sat","time":"11:30 AM - 3:00 PM","closed":false},{"day":"Sun","time":"11:30 AM - 3:00 PM","closed":false}]', '["takeout","delivery"]', NULL, NULL, NULL, 40.7473845, -73.9771526,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Nha Trang One', 'nha-trang-one-new-york', '', '', '', '+1-212-233-5948', 'https://nhatrangnyc.net/',
  COALESCE((SELECT id FROM categories WHERE slug = 'vietnamese-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '87 Baxter Street, New York, NY',
  'Vietnamese restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=nhatrangnyc.net&sz=256', NULL, NULL,
  'company', 0, '["Vietnamese","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Fri","time":"11:00 AM - 9:30 PM","closed":false},{"day":"Sat","time":"11:00 AM - 9:30 PM","closed":false}]', NULL, NULL, NULL, NULL, 40.7167899, -73.9996711,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Le Monde', 'le-monde-new-york', '', '', '', '+1 212-531-3939', 'https://lemondenyc.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'french-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '2885 Broadway, New York, NY',
  'French restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=lemondenyc.com&sz=256', NULL, NULL,
  'company', 0, '["French","Restaurant"]', 0, NULL,
  NULL, NULL, '["outdoor_seating","credit_cards"]', NULL, '["https://images.getbento.com/accounts/49376382f2c34498ad2be9608412e77a/media/images/20183Le_Monde_Logo-02_2.png?w=1200&fit=fill&auto=compress,format&cs=origin&h=600&bg=EDEDF1&pad=100"]', NULL, 40.8057782, -73.9658657,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Carmine''s Pizzeria', 'carmines-pizzeria-new-york', '', '', '', NULL, 'https.//www.carmineapizzeriamenu.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'italian-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '358 Graham Avenue, New York, NY',
  'Pizza restaurant in New York', NULL, NULL, NULL, NULL,
  'company', 0, '["Pizza","Restaurant"]', 0, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, 40.714968, -73.9443016,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Sol Et Soleil', 'sol-et-soleil-new-york', '', '', '', '+1-518-536-3183', 'https://soletsoleil.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '14 Bushwick Avenue, New York, NY',
  'Restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=soletsoleil.com&sz=256', NULL, NULL,
  'company', 0, '["Restaurant"]', 0, NULL,
  NULL, '[{"day":"Tue","time":"5:00 PM - 10:00 PM","closed":false},{"day":"Wed","time":"5:00 PM - 10:00 PM","closed":false},{"day":"Thu","time":"5:00 PM - 10:00 PM","closed":false},{"day":"Fri","time":"11:00 AM - 3:30 PM","closed":false},{"day":"Sat","time":"11:00 AM - 3:30 PM","closed":false},{"day":"Sun","time":"11:00 AM - 3:30 PM","closed":false}]', '["takeout","delivery","wheelchair","reservations"]', NULL, NULL, NULL, 40.7143441, -73.9420637,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Hard Rock Cafe', 'hard-rock-cafe-new-york', '', '', '', '+1 212-343-3355', 'https://www.hardrockcafe.com/location/new-york/',
  COALESCE((SELECT id FROM categories WHERE slug = 'american-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '1501 Broadway, New York, NY',
  'American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=hardrockcafe.com&sz=256', NULL, NULL,
  'company', 0, '["American","Restaurant"]', 0, NULL,
  NULL, NULL, '["delivery","wheelchair","reservations"]', NULL, NULL, NULL, 40.756994, -73.9865512,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Freemans', 'freemans-new-york', '', '', '', '+1-212-420-0012', 'https://www.freemansrestaurant.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'american-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '8 Freeman Alley, New York, NY',
  'American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=freemansrestaurant.com&sz=256', NULL, NULL,
  'company', 0, '["American","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Tue","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Wed","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Thu","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Fri","time":"11:00 AM - 2:00 AM","closed":false},{"day":"Sat","time":"10:00 AM - 2:00 AM","closed":false},{"day":"Sun","time":"10:00 AM - 11:00 PM","closed":false}]', NULL, NULL, '["http://static1.squarespace.com/static/55c8d2a4e4b0168e0edc0b4b/t/55d1edb9e4b0c75c3e23643c/1439821243966/Outside-hero-shot.jpg?format=1500w"]', NULL, 40.7219891, -73.9924423,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Aurora', 'aurora-new-york', '', '', '', '+1-718-388-5100', 'https://www.aurorabk.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'italian-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '70 Grand Street, New York, NY',
  'Italian restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=aurorabk.com&sz=256', NULL, NULL,
  'company', 0, '["Italian","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"12:00 PM - 11:00 PM","closed":false},{"day":"Tue","time":"12:00 PM - 11:00 PM","closed":false},{"day":"Wed","time":"12:00 PM - 11:00 PM","closed":false},{"day":"Thu","time":"12:00 PM - 11:00 PM","closed":false}]', NULL, NULL, '["http://static1.squarespace.com/static/634026d8a926e51d5a9c9ad1/t/634da6343a3bc732c6425562/1666033204113/_DSC0557-HDR-Edit+copy+3.jpg?format=1500w"]', NULL, 40.7156935, -73.9647329,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Tick Tock Diner', 'tick-tock-diner-new-york', '', '', '', '+1 212-268-8444', 'https://www.ticktockdinerny.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '481 8th Avenue, New York, NY',
  'Diner restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=ticktockdinerny.com&sz=256', NULL, NULL,
  'company', 0, '["Diner","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Wed","time":"12:00 AM - 12:00 AM","closed":false},{"day":"Thu","time":"12:00 AM - 12:00 AM","closed":false},{"day":"Fri","time":"12:00 AM - 12:00 AM","closed":false},{"day":"Sat","time":"12:00 AM - 12:00 AM","closed":false},{"day":"Sun","time":"12:00 AM - 12:00 AM","closed":false}]', '["takeout","reservations","credit_cards"]', NULL, '["http://static1.squarespace.com/static/591472963a041182fc132936/t/59400dde1b10e311b1f23ac9/1497370079431/headerLogo.png?format=1500w"]', NULL, 40.7524435, -73.9935503,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Giovanni', 'giovanni-new-york', '', '', '', NULL, 'https://www.giovanniventicinque.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'italian-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '25 East 83rd Street, New York, NY',
  'Italian restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=giovanniventicinque.com&sz=256', NULL, NULL,
  'company', 0, '["Italian","Restaurant"]', 0, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, 40.779131, -73.960536,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Vinegar Hill House', 'vinegar-hill-house-new-york', '', '', '', NULL, 'https://www.vinegarhillhouse.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'american-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '72 Hudson Avenue, New York, NY',
  'American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=vinegarhillhouse.com&sz=256', NULL, NULL,
  'company', 0, '["American","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"5:30 PM - 9:30 PM","closed":false},{"day":"Tue","time":"5:30 PM - 9:30 PM","closed":false},{"day":"Wed","time":"5:30 PM - 9:30 PM","closed":false},{"day":"Thu","time":"5:30 PM - 9:30 PM","closed":false},{"day":"Fri","time":"5:30 PM - 10:00 PM","closed":false},{"day":"Sat","time":"10:00 AM - 3:00 PM","closed":false},{"day":"Sun","time":"10:00 AM - 3:00 PM","closed":false}]', NULL, NULL, '["https://images.getbento.com/accounts/d11333a380f22ab53365ec947501aae4/media/images/85639VHH2.0_Text_Logo_cropped.jpg?w=1200&fit=fill&auto=compress,format&cs=origin&h=600&bg=EDEDF1&pad=100"]', NULL, 40.7027578, -73.9812369,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Junior''s', 'juniors-new-york', '', '', '', '+1 212-302-2000', 'https://www.juniorscheesecake.com/blog/restaurants/times-square/',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '1515 Broadway, New York, NY',
  'Restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=juniorscheesecake.com&sz=256', NULL, NULL,
  'company', 0, '["Restaurant"]', 0, NULL,
  NULL, NULL, '["outdoor_seating"]', NULL, '["http://www.juniorscheesecake.com/cdn/shop/files/Vector.svg?height=628&pad_color=ffffff&v=1716191822&width=1200"]', NULL, 40.7582151, -73.9866267,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Diner', 'diner-new-york', '', '', '', '+1-718-486-3077', 'https://www.dinernyc.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'american-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '85 Broadway, New York, NY',
  'American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=dinernyc.com&sz=256', NULL, NULL,
  'company', 0, '["American","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"6:00 PM - 12:00 PM","closed":false},{"day":"Tue","time":"6:00 PM - 12:00 PM","closed":false},{"day":"Wed","time":"6:00 PM - 12:00 PM","closed":false},{"day":"Thu","time":"6:00 PM - 12:00 PM","closed":false},{"day":"Fri","time":"11:00 AM - 12:00 PM","closed":false}]', '["takeout","outdoor_seating","reservations"]', NULL, '["https://images.getbento.com/2xT22bY6Rpe68JydsGxA_diner-logo.png?w=1200&fit=fill&auto=compress,format&cs=origin&h=600&bg=EDEDF1&pad=100"]', NULL, 40.7106766, -73.9655977,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Ako', 'ako-new-york', '', '', '', '+1-718-302-2035', 'https://akosushi.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'japanese-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '205 Bedford Avenue, New York, NY',
  'Japanese restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=akosushi.com&sz=256', NULL, NULL,
  'company', 0, '["Japanese","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Tue","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Wed","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Thu","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Fri","time":"12:00 PM - 11:00 PM","closed":false},{"day":"Sat","time":"12:00 PM - 11:00 PM","closed":false},{"day":"Sun","time":"12:00 PM - 10:00 PM","closed":false}]', NULL, NULL, NULL, NULL, 40.7169209, -73.9585388,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Joe''s Pizza', 'joes-pizza-new-york', '', '', '', '+1 212-366-1182', 'https://www.joespizzanyc.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'italian-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '7 Carmine Street, New York, NY',
  'Pizza restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=joespizzanyc.com&sz=256', NULL, NULL,
  'company', 0, '["Pizza","Restaurant"]', 0, NULL,
  NULL, NULL, NULL, NULL, '["http://static1.squarespace.com/static/5fb3405312797c6fcd738f7a/t/5fb346f9a35dc208e8165dff/1605584635837/IMG_7844.JPG?format=1500w"]', NULL, 40.7305467, -74.0020629,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Momo Sushi', 'momo-sushi-new-york', '', '', '', NULL, 'momosushishack.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'japanese-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '43 Bogart Street, New York, NY',
  'Japanese restaurant in New York', NULL, NULL, NULL, NULL,
  'company', 0, '["Japanese","Restaurant"]', 0, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, 40.7051487, -73.9333751,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Lombardi''s Pizza', 'lombardis-pizza-new-york', '', '', '', '+1-212-941-7994', 'https://www.firstpizza.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'italian-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '32 Spring Street, New York, NY',
  'Pizza restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=firstpizza.com&sz=256', NULL, NULL,
  'company', 0, '["Pizza","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Tue","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Wed","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Thu","time":"12:00 PM - 10:00 PM","closed":false},{"day":"Fri","time":"12:00 PM - 12:00 PM","closed":false},{"day":"Sat","time":"12:00 PM - 12:00 PM","closed":false},{"day":"Sun","time":"12:00 PM - 10:00 PM","closed":false}]', '["takeout","delivery","outdoor_seating"]', NULL, NULL, NULL, 40.7215933, -73.9956147,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Mộc Mạc', 'moc-mac-new-york', '', '', '', '+1-516-943-9347', 'https://mocmacnyc.com',
  COALESCE((SELECT id FROM categories WHERE slug = 'vietnamese-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '79 2nd Avenue, New York, NY',
  'Vietnamese restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=mocmacnyc.com&sz=256', NULL, NULL,
  'company', 0, '["Vietnamese","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"12:00 PM - 4:00 PM","closed":false},{"day":"Tue","time":"12:00 PM - 4:00 PM","closed":false},{"day":"Wed","time":"12:00 PM - 4:00 PM","closed":false},{"day":"Thu","time":"12:00 PM - 4:00 PM","closed":false},{"day":"Fri","time":"12:00 PM - 4:00 PM","closed":false},{"day":"Sat","time":"12:00 PM - 4:00 PM","closed":false},{"day":"Sun","time":"12:00 PM - 4:00 PM","closed":false}]', '["vegetarian"]', NULL, NULL, NULL, 40.7266326, -73.9893341,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Tom''s Restaurant', 'toms-restaurant-new-york', '', '', '', '+1 212-864-6137', 'https://tomsrestaurant.net/',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '2880 Broadway, New York, NY',
  'Diner restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=tomsrestaurant.net&sz=256', NULL, NULL,
  'company', 0, '["Diner","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"7:00 AM - 11:00 PM","closed":false},{"day":"Tue","time":"7:00 AM - 11:00 PM","closed":false},{"day":"Wed","time":"7:00 AM - 11:00 PM","closed":false},{"day":"Thu","time":"7:00 AM - 11:00 PM","closed":false},{"day":"Fri","time":"7:00 AM - 11:00 PM","closed":false},{"day":"Sat","time":"7:00 AM - 11:00 PM","closed":false},{"day":"Sun","time":"7:00 AM - 11:00 PM","closed":false}]', NULL, NULL, NULL, NULL, 40.8054509, -73.9654163,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'The River Café', 'the-river-cafe-new-york', '', '', '', '+1 718 522 5200', 'https://www.rivercafe.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '1 Water Street, New York, NY',
  'New American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=rivercafe.com&sz=256', NULL, NULL,
  'company', 0, '["New American","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"5:30 PM - 11:00 PM","closed":false},{"day":"Tue","time":"5:30 PM - 11:00 PM","closed":false},{"day":"Wed","time":"5:30 PM - 11:00 PM","closed":false},{"day":"Thu","time":"5:30 PM - 11:00 PM","closed":false},{"day":"Fri","time":"5:30 PM - 11:00 PM","closed":false},{"day":"Sat","time":"11:30 AM - 11:00 PM","closed":false},{"day":"Sun","time":"11:30 AM - 11:00 PM","closed":false}]', NULL, NULL, '["https://rivercafe.com/wp-content/uploads/revslider/spring/rivercafe-nyc-2020.jpg"]', NULL, 40.7037562, -73.994822,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Bill''s Townhouse', 'bills-townhouse-new-york', '', '', '', '+1 212-518-2727', 'https://www.billstownhouse.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'american-restaurants' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '57 East 54th Street, New York, NY',
  'American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=billstownhouse.com&sz=256', NULL, NULL,
  'company', 0, '["American","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Tue","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Wed","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Thu","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Fri","time":"11:00 AM - 11:00 PM","closed":false},{"day":"Sat","time":"5:00 PM - 10:00 PM","closed":false}]', NULL, NULL, NULL, NULL, 40.7601706, -73.9730036,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Four Seasons', 'four-seasons-new-york', '', '', '', NULL, 'https://www.fourseasonsrestaurant.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '99 East 52nd Street, New York, NY',
  'New American restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=fourseasonsrestaurant.com&sz=256', NULL, NULL,
  'company', 0, '["New American","Restaurant"]', 0, NULL,
  NULL, NULL, NULL, NULL, NULL, NULL, 40.7580948, -73.9720223,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

INSERT INTO submissions (
  uuid, company_name, slug, contact_name, email, phone_code, phone, website,
  category_id, country_id, city, state, hq_location,
  tagline, description, logo_url, founded_year, team_size,
  listing_mode, is_hiring, header_tags, verified, verified_at,
  lb_price_range, lb_hours, lb_amenities, lb_menu, lb_photos, lb_videos, lb_lat, lb_lng,
  status, payment_status, plan_id, user_id, created_at, updated_at
) SELECT
  UUID(), 'Smith & Wollensky', 'smith-wollensky-new-york', '', '', '', '+1-212-753-1530', 'https://www.smithandwollenskynyc.com/',
  COALESCE((SELECT id FROM categories WHERE slug = 'restaurants-by-cuisine' LIMIT 1), (SELECT id FROM categories WHERE slug = 'restaurants-food-drink' LIMIT 1), @lb_sector), @co_US, 'New York', 'NY', '797 3rd Avenue, New York, NY',
  'Steak House restaurant in New York', NULL, 'https://www.google.com/s2/favicons?domain=smithandwollenskynyc.com&sz=256', NULL, NULL,
  'company', 0, '["Steak House","Restaurant"]', 0, NULL,
  NULL, '[{"day":"Mon","time":"11:45 AM - 2:00 PM","closed":false},{"day":"Tue","time":"11:45 AM - 2:00 PM","closed":false},{"day":"Wed","time":"11:45 AM - 2:00 PM","closed":false},{"day":"Thu","time":"11:45 AM - 2:00 PM","closed":false},{"day":"Fri","time":"11:45 AM - 2:00 PM","closed":false},{"day":"Sat","time":"5:00 PM - 11:00 PM","closed":false},{"day":"Sun","time":"5:00 PM - 11:00 PM","closed":false}]', '["takeout","delivery","outdoor_seating","wheelchair","reservations","credit_cards"]', NULL, NULL, NULL, 40.7552548, -73.9709515,
  'pending', 'unpaid', @free_plan, NULL, NOW(), NOW();

-- ── GO LIVE (review in /iww-hq/submissions first, then run this) ──
-- UPDATE submissions SET status = 'active', activated_at = NOW()
--  WHERE listing_mode = 'company' AND status = 'pending' AND slug IN ('pedros-new-york', 'trudys-ice-cream-new-york', 'little-alley-new-york', 'nha-trang-one-new-york', 'le-monde-new-york', 'carmines-pizzeria-new-york', 'sol-et-soleil-new-york', 'hard-rock-cafe-new-york', 'freemans-new-york', 'aurora-new-york', 'tick-tock-diner-new-york', 'giovanni-new-york', 'vinegar-hill-house-new-york', 'juniors-new-york', 'diner-new-york', 'ako-new-york', 'joes-pizza-new-york', 'momo-sushi-new-york', 'lombardis-pizza-new-york', 'moc-mac-new-york', 'toms-restaurant-new-york', 'the-river-cafe-new-york', 'bills-townhouse-new-york', 'four-seasons-new-york', 'smith-wollensky-new-york');
