#!/usr/bin/env python3
"""
Generate SQL migration for Software & SaaS taxonomy replacement.
Reads: Software-SaaS-Taxonomy-900plus.xlsx
Writes: database/migration-software-saas-taxonomy.sql

Replaces 12 old L2 + ~95 old L3 with 37 new L2 + 1,783 new L3.
"""

import openpyxl
import re
import os
from collections import OrderedDict

# ─── Config ────────────────────────────────────────────────────────
EXCEL = r"C:\Users\AADIL PARMAR\Downloads\Software-SaaS-Taxonomy-900plus.xlsx"
SHEET = "Software & SaaS Navigation"
L1_SLUG = "software-saas"
L1_LEVEL = 1
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "database")
OUT_FILE = os.path.join(OUT_DIR, "migration-software-saas-taxonomy.sql")
COLOR = "#3B82F6"  # blue for Software & SaaS

# ─── Helpers ───────────────────────────────────────────────────────
def slugify(name):
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)       # strip non-alphanumeric
    s = re.sub(r"[\s_]+", "-", s)             # spaces/underscores → hyphens
    s = re.sub(r"-{2,}", "-", s)              # collapse multiple hyphens
    s = s.strip("-")                          # no leading/trailing hyphens
    return s

def esc(val):
    """Escape single quotes for SQL."""
    return val.replace("'", "''")

# Track used slugs globally to prevent collisions
used_slugs = set()

def unique_slug(name, parent_name=None):
    base = slugify(name)
    if base not in used_slugs:
        used_slugs.add(base)
        return base
    # Disambiguate with parent context
    if parent_name:
        candidate = slugify(f"{parent_name} {name}")
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate
    # Numeric suffix fallback
    i = 2
    while f"{base}-{i}" in used_slugs:
        i += 1
    final = f"{base}-{i}"
    used_slugs.add(final)
    return final

# ─── Read Excel ────────────────────────────────────────────────────
print(f"Reading {EXCEL} ...")
wb = openpyxl.load_workbook(EXCEL, read_only=True, data_only=True)
ws = wb[SHEET]

# Build ordered L2 → [L3, ...] map
taxonomy = OrderedDict()
for i, row in enumerate(ws.iter_rows(values_only=True), 1):
    if i == 1:
        continue  # skip header
    l2 = str(row[2]).strip() if row[2] else None
    l3 = str(row[3]).strip() if row[3] else None
    if not l2 or not l3:
        continue
    if l2 not in taxonomy:
        taxonomy[l2] = []
    taxonomy[l2].append(l3)

wb.close()

l2_count = len(taxonomy)
l3_count = sum(len(v) for v in taxonomy.values())
print(f"Parsed: {l2_count} L2 categories, {l3_count} L3 subcategories")

# ─── Generate SQL ──────────────────────────────────────────────────
lines = []
lines.append("-- ═══════════════════════════════════════════════════════════════")
lines.append("-- Software & SaaS Taxonomy Migration")
lines.append(f"-- Replaces old 12 L2 + ~95 L3 with {l2_count} L2 + {l3_count} L3")
lines.append("-- Generated by generate-software-saas-migration.py")
lines.append("-- ═══════════════════════════════════════════════════════════════")
lines.append("")

# STEP 1: Delete SEO content for old L2/L3
lines.append("-- ═══ STEP 1: Delete SEO content for old Software & SaaS L2/L3 ═══")
lines.append(f"""DELETE FROM category_seo_content
WHERE category_id IN (
  SELECT id FROM (
    SELECT id FROM categories
    WHERE parent_id IN (
      SELECT id FROM categories WHERE parent_id = (
        SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
      )
    )
    UNION
    SELECT id FROM categories
    WHERE parent_id = (
      SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
    )
  ) AS ids
);""")
lines.append("")

# STEP 2: Nullify submission category_id
lines.append("-- ═══ STEP 2: Nullify submission category_id (preserve listings) ═══")
lines.append(f"""UPDATE submissions SET category_id = NULL
WHERE category_id IN (
  SELECT id FROM (
    SELECT id FROM categories
    WHERE parent_id IN (
      SELECT id FROM categories WHERE parent_id = (
        SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
      )
    )
    UNION
    SELECT id FROM categories
    WHERE parent_id = (
      SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
    )
  ) AS ids
);""")
lines.append("")

# STEP 3: Delete listing types for old L3s
lines.append("-- ═══ STEP 3: Delete listing types for old Software & SaaS L3s ═══")
lines.append(f"""DELETE FROM listing_types
WHERE category_id IN (
  SELECT id FROM (
    SELECT id FROM categories
    WHERE parent_id IN (
      SELECT id FROM categories WHERE parent_id = (
        SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
      )
    )
  ) AS ids
);""")
lines.append("")

# STEP 4: Delete old L3 categories
lines.append("-- ═══ STEP 4: Delete old L3 categories ═══")
lines.append(f"""DELETE FROM categories
WHERE level = 3 AND parent_id IN (
  SELECT id FROM (
    SELECT id FROM categories WHERE parent_id = (
      SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
    )
  ) AS ids
);""")
lines.append("")

# STEP 5: Delete old L2 categories
lines.append("-- ═══ STEP 5: Delete old L2 categories ═══")
lines.append(f"""DELETE FROM categories
WHERE level = 2 AND parent_id = (
  SELECT id FROM (
    SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
  ) AS t1
);""")
lines.append("")

# STEP 6: Insert new L2 categories
lines.append(f"-- ═══ STEP 6: Insert {l2_count} new L2 categories ═══")
for idx, l2_name in enumerate(taxonomy.keys()):
    slug = unique_slug(l2_name)
    sort = (idx + 1) * 10
    lines.append(
        f"INSERT INTO categories (name, slug, level, parent_id, is_active, is_launched, is_navigation, sort_order, color) "
        f"SELECT '{esc(l2_name)}', '{slug}', 2, id, 1, 1, 1, {sort}, '{COLOR}' "
        f"FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL};"
    )
lines.append("")

# STEP 7: Insert new L3 subcategories
lines.append(f"-- ═══ STEP 7: Insert {l3_count} new L3 subcategories ═══")
for l2_name, l3_list in taxonomy.items():
    l2_slug = slugify(l2_name)
    # Use the actual slug we generated (might have suffix)
    # Find it in used_slugs by checking what we generated for this L2
    # Actually, we need to track L2 slugs explicitly
    lines.append(f"-- {l2_name} ({len(l3_list)} L3s)")
    for j, l3_name in enumerate(l3_list):
        l3_slug = unique_slug(l3_name, l2_name)
        sort = (j + 1) * 10
        lines.append(
            f"INSERT INTO categories (name, slug, level, parent_id, is_active, is_launched, is_navigation, sort_order, color) "
            f"SELECT '{esc(l3_name)}', '{l3_slug}', 3, id, 1, 1, 1, {sort}, '{COLOR}' "
            f"FROM categories WHERE slug = '{slugify(l2_name)}' AND level = 2 LIMIT 1;"
        )
    lines.append("")

# STEP 8: Set colors
lines.append("-- ═══ STEP 8: Set color on all new Software & SaaS L2/L3 ═══")
lines.append(f"""UPDATE categories SET color = '{COLOR}'
WHERE level IN (2, 3) AND (
  parent_id = (SELECT id FROM (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}) AS t1)
  OR parent_id IN (SELECT id FROM (SELECT id FROM categories WHERE level = 2 AND parent_id = (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL})) AS t2)
);""")
lines.append("")
lines.append("-- ═══ DONE ═══")
lines.append(f"-- Verify: SELECT COUNT(*) FROM categories WHERE level = 2 AND parent_id = (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = 1);")
lines.append(f"-- Expected: {l2_count}")
lines.append(f"-- Verify: SELECT COUNT(*) FROM categories WHERE level = 3 AND parent_id IN (SELECT id FROM categories WHERE level = 2 AND parent_id = (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = 1));")
lines.append(f"-- Expected: {l3_count}")

# ─── Write SQL ─────────────────────────────────────────────────────
os.makedirs(OUT_DIR, exist_ok=True)
with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written: {OUT_FILE}")
print(f"  {l2_count} L2 INSERTs + {l3_count} L3 INSERTs")

# Also print L2 slug map for the remapping script
print("\nL2 slug map:")
for l2_name in taxonomy.keys():
    s = slugify(l2_name)
    print(f"  {l2_name} -> {s}")
