#!/usr/bin/env python3
"""
Generate SQL migration for IT Services & Agencies taxonomy replacement.
Reads: IT-Services-Agencies-Taxonomy-900plus.xlsx
Writes: database/migration-it-services-taxonomy.sql

Replaces 5 old L2 + 45 old L3 with 43 new L2 + 1,596 new L3.
"""

import openpyxl
import re
import os
import sys
from collections import OrderedDict

sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf-8', buffering=1)

# ─── Config ────────────────────────────────────────────────────────
EXCEL = r"C:\Users\AADIL PARMAR\Downloads\IT-Services-Agencies-Taxonomy-900plus.xlsx"
SHEET = "IT Services Navigation"
L1_SLUG = "it-services-agencies"
L1_LEVEL = 1
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "database")
OUT_FILE = os.path.join(OUT_DIR, "migration-it-services-taxonomy.sql")
COLOR = "#14B8A6"  # teal for IT Services & Agencies

# ─── Helpers ───────────────────────────────────────────────────────
def slugify(name):
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-{2,}", "-", s)
    return s.strip("-")

def esc(val):
    return val.replace("'", "''")

# Pre-load ALL existing slugs from DB to prevent cross-sector collisions
import pymysql
_conn = pymysql.connect(host='server46.hostwhitelabel.com', port=3306,
    user='cdbrisgy_infowebworld2026', password='infowebworld@2026',
    database='cdbrisgy_infowebworld', charset='utf8mb4')
_cur = _conn.cursor()
_cur.execute('SELECT slug FROM categories')
used_slugs = {r[0] for r in _cur.fetchall()}
_conn.close()
print(f"Pre-loaded {len(used_slugs)} existing slugs from DB")

def unique_slug(name, parent_name=None):
    base = slugify(name)
    if base not in used_slugs:
        used_slugs.add(base)
        return base
    if parent_name:
        candidate = slugify(f"{parent_name} {name}")
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate
    i = 2
    while f"{base}-{i}" in used_slugs:
        i += 1
    final = f"{base}-{i}"
    used_slugs.add(final)
    return final

# ─── Read Excel ────────────────────────────────────────────────────
print(f"Reading {EXCEL} ...")
wb = openpyxl.load_workbook(EXCEL, read_only=True, data_only=True)
ws = wb[SHEET]

taxonomy = OrderedDict()
for i, row in enumerate(ws.iter_rows(values_only=True), 1):
    if i == 1:
        continue
    l2 = str(row[2]).strip() if row[2] else None
    l3 = str(row[3]).strip() if row[3] else None
    if not l2 or not l3:
        continue
    if l2 not in taxonomy:
        taxonomy[l2] = []
    taxonomy[l2].append(l3)

wb.close()

l2_count = len(taxonomy)
l3_count = sum(len(v) for v in taxonomy.values())
print(f"Parsed: {l2_count} L2 categories, {l3_count} L3 subcategories")

# ─── Generate SQL ──────────────────────────────────────────────────
lines = []
lines.append("-- =================================================================")
lines.append("-- IT Services & Agencies Taxonomy Migration")
lines.append(f"-- Replaces old 5 L2 + 45 L3 with {l2_count} L2 + {l3_count} L3")
lines.append("-- Generated by generate-it-services-migration.py")
lines.append("-- =================================================================")
lines.append("")

# STEP 1: Delete SEO content
lines.append("-- === STEP 1: Delete SEO content for old IT Services L2/L3 ===")
lines.append(f"""DELETE FROM category_seo_content
WHERE category_id IN (
  SELECT id FROM (
    SELECT id FROM categories
    WHERE parent_id IN (
      SELECT id FROM categories WHERE parent_id = (
        SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
      )
    )
    UNION
    SELECT id FROM categories
    WHERE parent_id = (
      SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
    )
  ) AS ids
);""")
lines.append("")

# STEP 2: Nullify submission category_id
lines.append("-- === STEP 2: Nullify submission category_id ===")
lines.append(f"""UPDATE submissions SET category_id = NULL
WHERE category_id IN (
  SELECT id FROM (
    SELECT id FROM categories
    WHERE parent_id IN (
      SELECT id FROM categories WHERE parent_id = (
        SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
      )
    )
    UNION
    SELECT id FROM categories
    WHERE parent_id = (
      SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
    )
  ) AS ids
);""")
lines.append("")

# STEP 3: Delete listing types
lines.append("-- === STEP 3: Delete listing types for old IT Services L3s ===")
lines.append(f"""DELETE FROM listing_types
WHERE category_id IN (
  SELECT id FROM (
    SELECT id FROM categories
    WHERE parent_id IN (
      SELECT id FROM categories WHERE parent_id = (
        SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
      )
    )
  ) AS ids
);""")
lines.append("")

# STEP 4: Delete old L3
lines.append("-- === STEP 4: Delete old L3 categories ===")
lines.append(f"""DELETE FROM categories
WHERE level = 3 AND parent_id IN (
  SELECT id FROM (
    SELECT id FROM categories WHERE parent_id = (
      SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
    )
  ) AS ids
);""")
lines.append("")

# STEP 5: Delete old L2
lines.append("-- === STEP 5: Delete old L2 categories ===")
lines.append(f"""DELETE FROM categories
WHERE level = 2 AND parent_id = (
  SELECT id FROM (
    SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}
  ) AS t1
);""")
lines.append("")

# STEP 6: Insert new L2
lines.append(f"-- === STEP 6: Insert {l2_count} new L2 categories ===")
for idx, l2_name in enumerate(taxonomy.keys()):
    slug = unique_slug(l2_name)
    sort = (idx + 1) * 10
    lines.append(
        f"INSERT INTO categories (name, slug, level, parent_id, is_active, is_launched, is_navigation, sort_order, color) "
        f"SELECT '{esc(l2_name)}', '{slug}', 2, id, 1, 1, 1, {sort}, '{COLOR}' "
        f"FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL};"
    )
lines.append("")

# STEP 7: Insert new L3
lines.append(f"-- === STEP 7: Insert {l3_count} new L3 subcategories ===")
for l2_name, l3_list in taxonomy.items():
    l2_slug = slugify(l2_name)
    lines.append(f"-- {l2_name} ({len(l3_list)} L3s)")
    for j, l3_name in enumerate(l3_list):
        l3_slug = unique_slug(l3_name, l2_name)
        sort = (j + 1) * 10
        lines.append(
            f"INSERT INTO categories (name, slug, level, parent_id, is_active, is_launched, is_navigation, sort_order, color) "
            f"SELECT '{esc(l3_name)}', '{l3_slug}', 3, id, 1, 1, 1, {sort}, '{COLOR}' "
            f"FROM categories WHERE slug = '{l2_slug}' AND level = 2 LIMIT 1;"
        )
    lines.append("")

# STEP 8: Set colors
lines.append("-- === STEP 8: Set color on all new IT Services L2/L3 ===")
lines.append(f"""UPDATE categories SET color = '{COLOR}'
WHERE level IN (2, 3) AND (
  parent_id = (SELECT id FROM (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL}) AS t1)
  OR parent_id IN (SELECT id FROM (SELECT id FROM categories WHERE level = 2 AND parent_id = (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = {L1_LEVEL})) AS t2)
);""")
lines.append("")
lines.append("-- === DONE ===")
lines.append(f"-- Verify L2: SELECT COUNT(*) FROM categories WHERE level = 2 AND parent_id = (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = 1);")
lines.append(f"-- Expected: {l2_count}")
lines.append(f"-- Verify L3: SELECT COUNT(*) FROM categories WHERE level = 3 AND parent_id IN (SELECT id FROM categories WHERE level = 2 AND parent_id = (SELECT id FROM categories WHERE slug = '{L1_SLUG}' AND level = 1));")
lines.append(f"-- Expected: {l3_count}")

os.makedirs(OUT_DIR, exist_ok=True)
with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written: {OUT_FILE}")
print(f"  {l2_count} L2 + {l3_count} L3 INSERTs")
