/* Merge g1..g7.json fragments → scripts/pro-services-200.data.mjs (COMPANIES_RAW).
   Validates, dedupes by domain, reports coverage. Run after _extract-g3.mjs. */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const DIR = new URL('./', import.meta.url)
const FILES = ['g1.json', 'g2.json', 'g3.json', 'g4.json', 'g5.json', 'g6.json', 'g7.json']
const VALID_SLUGS = new Set([
  'accounting-tax-services', 'architecture-engineering-design', 'business-consulting-pro',
  'coaching-professional-development', 'corporate-event-planning-production', 'corporate-training-learning',
  'financial-advisory-planning', 'hr-staffing-recruiting', 'insurance-professional-services',
  'investigative-forensic-services', 'investment-banking-capital-markets', 'legal-services-pro',
  'marketing-advertising-communications', 'real-estate-professional-services', 'risk-compliance-audit',
  'sustainability-esg-environmental-consulting', 'technology-advisory-services',
  'translation-language-services', 'writing-editing-research-services',
])

const frags = []
for (const f of FILES) {
  const p = new URL(f, DIR)
  if (!existsSync(p)) { console.warn('  (missing) ' + f); continue }
  let arr
  try { arr = JSON.parse(readFileSync(p, 'utf8')) } catch (e) { console.error('  BAD JSON ' + f + ': ' + e.message); continue }
  if (!Array.isArray(arr)) { console.error('  NOT ARRAY ' + f); continue }
  console.log('  ' + f + ': ' + arr.length)
  frags.push(arr)
}
/* Round-robin interleave so the downstream 200-cap stays evenly spread across
   all fields instead of starving the last fragment (e.g. corporate events). */
let all = []
let any = true
while (any) {
  any = false
  for (const fr of frags) { if (fr.length) { all.push(fr.shift()); any = true } }
}

const seen = new Set()
const out = []
let dropped = 0
const badSlug = []
for (const c of all) {
  if (!c || !c.company_name || !c.domain) { dropped++; continue }
  const dom = String(c.domain).toLowerCase().replace(/^www\./, '')
  if (seen.has(dom)) { dropped++; continue }
  if (!VALID_SLUGS.has(c.category_slug)) badSlug.push(c.company_name + ' → ' + c.category_slug)
  seen.add(dom)
  out.push(c)
}

const byCat = {}, byCountry = {}
for (const c of out) {
  byCat[c.category_slug] = (byCat[c.category_slug] || 0) + 1
  byCountry[c.country_code] = (byCountry[c.country_code] || 0) + 1
}

const banner = `/* AUTO-GENERATED by scripts/research-ps/_merge.mjs — do not edit by hand.\n   ${out.length} real, web-verified professional-services firms from g1..g7.json. */\n`
writeFileSync(new URL('../pro-services-200.data.mjs', DIR), banner + 'export const COMPANIES_RAW = ' + JSON.stringify(out) + '\n')

console.log('\nMerged: ' + out.length + ' firms (dropped ' + dropped + ' dup/invalid)')
console.log('Categories: ' + Object.keys(byCat).length + '/19  ' + JSON.stringify(byCat))
console.log('Countries: ' + Object.keys(byCountry).length + '  ' + JSON.stringify(byCountry))
if (badSlug.length) console.warn('⚠ UNKNOWN category_slug (will fall back to sector L1):\n  ' + badSlug.join('\n  '))
