/* Merge enrich-g1..g7.json → scripts/pro-services-200.enrich.mjs (ENRICH_RAW).
   Keyed by domain; prefers non-empty fields when a domain appears twice. */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const DIR = new URL('./', import.meta.url)
const FILES = ['enrich-g1.json', 'enrich-g2.json', 'enrich-g3.json', 'enrich-g4.json', 'enrich-g5.json', 'enrich-g6.json', 'enrich-g7.json']

let all = []
for (const f of FILES) {
  const p = new URL(f, DIR)
  if (!existsSync(p)) { console.warn('  (missing) ' + f); continue }
  let a
  try { a = JSON.parse(readFileSync(p, 'utf8')) } catch (e) { console.error('  BAD JSON ' + f + ': ' + e.message); continue }
  if (!Array.isArray(a)) { console.error('  NOT ARRAY ' + f); continue }
  console.log('  ' + f + ': ' + a.length)
  all = all.concat(a)
}

const map = new Map()
for (const e of all) {
  if (!e || !e.domain) continue
  const d = String(e.domain).toLowerCase().replace(/^www\./, '')
  const prev = map.get(d) || { domain: d, intro_video_url: null, awards: [], notable_clients: [] }
  map.set(d, {
    domain: d,
    intro_video_url: e.intro_video_url || prev.intro_video_url || null,
    awards: (Array.isArray(e.awards) && e.awards.length) ? e.awards : prev.awards,
    notable_clients: (Array.isArray(e.notable_clients) && e.notable_clients.length) ? e.notable_clients : prev.notable_clients,
  })
}
const out = [...map.values()]
const banner = '/* AUTO-GENERATED by scripts/research-ps/_merge-enrich.mjs — do not edit by hand. */\n'
writeFileSync(new URL('../pro-services-200.enrich.mjs', DIR), banner + 'export const ENRICH_RAW = ' + JSON.stringify(out) + '\n')

let v = 0, a2 = 0, c2 = 0
for (const e of out) { if (e.intro_video_url) v++; if (e.awards.length) a2++; if (e.notable_clients.length) c2++ }
console.log('\nEnrich merged: ' + out.length + ' domains — ' + a2 + ' with awards, ' + v + ' with video, ' + c2 + ' with clients')
